### ISSUE TITLE
Timezone support in checks not working

### ISSUE THREAD

**Issue by andrew-pickin-epi** [sensu/sensu-go#4385] opened 2021-08-13 09:49 UTC
Including CRON-TZ or TZ in cron specification is rejected as invalid. 

## Expected Behavior
https://github.com/sensu/sensu-go/pull/3395 
Suggests that `CRON_TZ=Asia/Tokyo 0 * * * *` is valid. However this is rejected as invalid.

## Current Behavior
Specifying TZ or CRON_TZ in cron is rejected.

## Possible Solution
See 3395 above

## Steps to Reproduce (for bugs)
See Above

## Context
Servers run as UTC. Checks required for real-world events that happen in localtime.

## Your Environment
Docker image sensu/sensu:6.2.5
AWS Linux 2

**Comment by calebhailey** [comment] 2021-08-17 21:35
Just verified that [the examples in our docs](https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-schedule/checks/#example-cron-checks) are not accepted in version 6.4.0, and there's not much of an explanation in the logs: 

```
{"component":"apid","duration":"2.439ms","level":"info","method":"PUT","msg":"request completed","path":"/api/core/v2/namespaces/default/checks/cron_test","size":72,"status":400,"time":"2021-08-17T21:30:20Z","u
ser":"sensu"}
```

To be more specific, I tried both of the following configuration templates: 

```yaml
---
type: CheckConfig
api_version: core/v2
metadata:
  name: cron_test
spec:
  command: "true"
  cron: 'CRON_TZ=Asia/Tokyo * * * * *'
  handlers: []
  publish: true
  subscriptions:
  - system/linux
---
type: CheckConfig
api_version: core/v2
metadata:
  name: cron_test
spec:
  command: "true"
  cron: 'TZ=Asia/Tokyo * * * * *'
  handlers: []
  publish: true
  subscriptions:
  - system/linux
```

I get the following output: 

```
$ sensuctl create -f 4385.yaml
Error: error putting resource #0 with name "cron_test" and namespace "default" (/api/core/v2/namespaces/default/checks/cron_test): resource is invalid: check cron string is invalid         
```

**Comment by hillaryfraley** [comment] 2021-08-17 21:50
@calebhailey -- @mgibson323 and I tested some cron issues in July -- we were able to use the documented examples. Our notes are in this docs issue: https://github.com/sensu/sensu-docs/issues/3245

**Comment by andrew-pickin-epi** [comment] 2021-08-18 10:32
Cron tasks with time zone fail when created via gui or ansible modules.

**Comment by andrew-pickin-epi** [comment] 2021-09-01 08:43
Closed in error

**Comment by andrew-pickin-epi** [comment] 2021-09-30 09:02
Is there any likelihood of this being addressed soon?

**Comment by portertech** [comment] 2021-11-01 17:32
We need to verify the desired CRON_TZ values exist in the timezone database.

**Comment by mgibson323** [comment] 2021-11-10 17:21
Another customer is reporting CRON issues but I am not sure it's related to this ticket - in the Web UI they see some odd text in the description of the schedule - see attached screenshot: 

<img width="1423" alt="E6_rj8rWEAg4zBp" src="https://user-images.githubusercontent.com/4676632/141161800-0d3ce1cb-a827-4579-8994-3895ac613db3.png">

"Every London seconds, starting at CRON_TZ=Europe seconds past the minute, at 32 minutes past the hour, at 07:00 PM, only on Monday, Tuesday, Wednesday, Thursday, Friday, and Saturday"

**Comment by jamesdphillips** [comment] 2021-11-10 18:07
I'm wondering if our docker images have incomplete zone info, it looks like go will look for the first available source and use it. If the source was incomplete it will not continue on and try other sources.

Sources: https://github.com/golang/go/blob/2ebe77a2fda1ee9ff6fd9a3e08933ad1ebaea039/src/time/zoneinfo_unix.go#L19-L27
Lookup: https://github.com/golang/go/blob/2ebe77a2fda1ee9ff6fd9a3e08933ad1ebaea039/src/time/zoneinfo_read.go#L519-L530

**Comment by amdprophet** [comment] 2021-11-19 19:08
I've confirmed that the example in https://github.com/sensu/sensu-go/issues/4385#issuecomment-900647423 no longer errors with the change from [sensu/sensu#29](https://github.com/sensu/sensu-docker/pull/29).

I'm going to look into outputting a better error when tzdata does not exist on the backend.

**Comment by amdprophet** [comment] 2021-11-24 17:47
This has ben fixed by https://github.com/sensu/sensu-docker/pull/29 and https://github.com/sensu/sensu-go/pull/4511.

**Closed by amdprophet** 2021-11-24 17:47 UTC
Labels: bug
