### ISSUE TITLE
Support chain certificates in services and utilities

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#3831] opened 2020-06-05 21:03 UTC
## Feature Suggestion

Sensu services and utilities should support certificate chains for parameter related to TLS certificates.

## Context

Recommended practices for PKI typically involve the use of one or more intermediate CAs. Increasingly, paid CAs deliver their products to end users as a single file containing the server certificate, followed by the CA certificate(s) for any intermediate CAs. 

We should make life easier for administrators by detecting chain cert files and automatically processing for use with our components secured via TLS.

**Comment by portertech** [comment] 2020-06-08 17:31
Relevant support ticket https://secure.helpscout.net/conversation/1117130112/20508?folderId=1420761

**Comment by ccressent** [comment] 2020-06-24 22:39
@cwjohnston 
I've spent quite a bit of time testing many, many X509 certificates in all the parts of Sensu that can make use of them for TLS (sensuctl, agent, API, etcd, dashboard, ...). Here is a summary of my notes and conclusions:

- All types of certificate chains are supported everywhere with the following caveat: the leaf certificate in the chain (that is the certificate that the program will use to show its own identity) has to be listed first in the PEM file. This is due to the way the `crypto/tls` Go standard library works; it just always makes that assumption.
  
  Unless one is using a well defined file format like PKCS#7 or PKCS#12, the order in which certificates should be presented when there are intermediate certificates involved is not well defined. For some programs, the leaf certificate should appear first. For other programs, it should follow the intermediate certificates and be last. Other programs do not care and figure it out. We're in the first case for any program that uses the Go standard library, like Sensu.

- We do not support the [PKCS#12 format](https://en.wikipedia.org/wiki/PKCS_12) to supply the certificates and key as one bundle. We only support PEM, certificate and key have to be provided separately (various `--cert-file` and `--key-file` options respectively) and the key cannot be encrypted.

- A common mistake that I've seen is that people make their program send the leaf certificate alone instead of the whole chain. This is incorrect and is a common source of "certificate not signed by trusted authority" errors. The whole chain needs to be presented to the remote so that it can determine if it trusts the leaf through the presented chain.

- The `bad certificate` error seen in their logs comes from etcd, and I was only able to reproduce it by setting up TLS for etcd and _not_ setting the correct `advertise-client-urls` and `listen-client-urls` options for etcd. What seems to happen is that etcd tries to use TLS, but since the default value for those `client-urls` options are for non-TLS connections, you end up with an error. [This `etcd` guide](https://etcd.io/docs/v3.3.12/op-guide/security/) should help with fine tuning all those settings in a coherent manner. In particular, just setting those `client-urls` options in my setup to `httpS://localhost:2379` made the error disappear.

I hope these comments help you resolve the issue that customer is facing; in any case don't hesitate to give me a shout if you have questions: I've learned a tremendous lot about TLS/X509 while investigating this and I'm more than happy to share my new knowledge with the team!

As there is definitely support for certificate chains in all of Sensu already, I'm closing this issue.

**Closed by ccressent** 2020-06-24 22:39 UTC
Labels: component:transport, needs-investigation
