### ISSUE TITLE
Logs overwhelmed with statsd errors when agent starts up

### ISSUE THREAD

**Issue by mercul3s** [sensu/sensu-go#1659] opened 2018-06-07 22:54 UTC
In testing for something else, I'm noticing the agent statsd is generating a ton of log messages (many per second):
```
Jun 07 21:54:08 sensu-beans sensu-agent[65975]: {"level":"warning","msg":"Error reading from socket: read udp 127.0.0.1:8125: recvmmsg: function not implemented","time":"2018-06-07T21:54:08Z"}
Jun 07 21:54:08 sensu-beans sensu-agent[65975]: {"level":"warning","msg":"Error reading from socket: read udp 127.0.0.1:8125: recvmmsg: function not implemented","time":"2018-06-07T21:54:08Z"}
Jun 07 21:54:08 sensu-beans sensu-agent[65975]: {"level":"warning","msg":"Error reading from socket: read udp 127.0.0.1:8125: recvmmsg: function not implemented","time":"2018-06-07T21:54:08Z"}
Jun 07 21:54:08 sensu-beans sensu-agent[65975]: {"level":"warning","msg":"Error reading from socket: read udp 127.0.0.1:8125: recvmmsg: function not implemented","time":"2018-06-07T21:54:08Z"}
Jun 07 21:54:08 sensu-beans sensu-agent[65975]: {"level":"warning","msg":"Error reading from socket: read udp 127.0.0.1:8125: recvmmsg: function not implemented","time":"2018-06-07T21:54:08Z"}
Jun 07 21:54:08 sensu-beans sensu-agent[65975]: {"level":"warning","msg":"Error reading from socket: read udp 127.0.0.1:8125: recvmmsg: function not implemented","time":"2018-06-07T21:54:08Z"}
Jun 07 21:54:08 sensu-beans sensu-agent[65975]: {"level":"warning","msg":"Error reading from socket: read udp 127.0.0.1:8125: recvmmsg: function not implemented","time":"2018-06-07T21:54:08Z"}
Jun 07 21:54:08 sensu-beans sensu-agent[65975]: {"level":"warning","msg":"Error reading from socket: read udp 127.0.0.1:8125: recvmmsg: function not implemented","time":"2018-06-07T21:54:08Z"}
Jun 07 21:54:08 sensu-beans sensu-agent[65975]: {"level":"warning","msg":"Error reading from socket: read udp 127.0.0.1:8125: recvmmsg: function not implemented","time":"2018-06-07T21:54:08Z"}
Jun 07 21:54:08 sensu-beans sensu-agent[65975]: {"level":"warning","msg":"Error reading from socket: read udp 127.0.0.1:8125: recvmmsg: function not implemented","time":"2018-06-07T21:54:08Z"}
Jun 07 21:54:08 sensu-beans sensu-agent[65975]: {"level":"warning","msg":"Error reading from socket: read udp 127.0.0.1:8125: recvmmsg: function not implemented","time":"2018-06-07T21:54:08Z"}
```
## Expected Behavior
Error messages should not overwhelm the logs - in this case, if a statsd component isn't working, it should probably just log once at start and then continue.

## Current Behavior
Statsd error logging: can't stop, won't stop.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
sensu-backend version 2.0.0-nightly#3d94a0b, build 3d94a0b86ae03d723e1ea06e73e89b142da5bbc1, built 2018-06-05T09:21:52+0000
sensu-agent version 2.0.0-nightly#3d94a0b, build 3d94a0b86ae03d723e1ea06e73e89b142da5bbc1, built 2018-06-05T09:23:04+0000
sensu-ctl version 2.0.0-nightly#3d94a0b, build 3d94a0b86ae03d723e1ea06e73e89b142da5bbc1, built 2018-06-05T09:23:24+0000
* Installation method (packages, binaries, docker etc.):
apt package
* Operating System and version (e.g. Ubuntu 14.04):
Ubuntu 16.04.4 20160601 lx container

**Comment by mercul3s** [comment] 2018-06-07 22:58
I think this is where the logging is happening in gostatsd:
https://github.com/atlassian/gostatsd/blob/97983f066a9a9039c19e964a88016c9b55cc9f34/pkg/statsd/receiver.go#L82-L92

**Comment by annaplotkin** [comment] 2018-11-05 18:42
We believe this has been resolved.

**Comment by axisofentropy** [comment] 2019-01-04 20:37
How was this resolved @annaplotkin ? I'm seeing this in 5.1.0.

**Comment by nikkiki** [comment] 2019-01-04 20:49
@axisofentropy I believe this issue was intermittent and difficult to reproduce. I'm not sure a specific change was made to resolve it, so I can go ahead and reopen this since you've run into it in 5.1.0.

**Comment by palourde** [comment] 2019-05-29 14:39
It's been a long time but please feel free to let us know if you still see this behavior with the latest Sensu Go release. I don't believe we ever saw it since then.

**Comment by agoddard** [comment] 2021-02-11 17:05
This see,s to have popped up again in 6.0, reopening for investigation

**Comment by amdprophet** [comment] 2021-12-03 02:39
This will happen if the kernel does not support the `recvmsg` syscall. The statsd feature will need to be disabled on any hosts with kernels that lack support.

One example of where this can specifically happen is on LX-branded zones on SmartOS/OmniOS. I suspect this is due to `recvmsg` not being implemented in whatever is translating Linux syscalls to native syscalls.

This may change in the future if we update or replace the statsd library that we depend on. Closing this as it's not a configuration we can currently support.

**Closed by amdprophet** 2021-12-03 02:39 UTC
Labels: component:agent
