### ISSUE TITLE
Sensu-go 5.1.1 backend is crashing

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#2638] opened 2019-01-25 00:27 UTC
## Expected Behavior

I'd expect sensu-puppet tests that passed with 5.1.0 to pass with 5.1.1.

## Current Behavior

Currently several tests are failing here: https://travis-ci.org/sensu/sensu-puppet/jobs/484138033

I see things like this:

```
 Error: Failed to apply catalog: Execution of '/usr/bin/sensuctl mutator list --all-namespaces --format json' returned 1: Error: Get https://sensu_backend:8080/api/core/v2/mutators: dial tcp 172.17.0.3:8080: connect: connection refused
```

Then later `sensuctl` commands are successful even though the service was not restarted.  My hunch is that sensu-backend is crashing and systemd is automatically restarting the daemon.

## Steps to Reproduce (for bugs)

I am not sure yet.

## Context

I am working with @ghoneycutt on sensu-puppet module and acceptance tests are failing with latest 5.1.1 release and did not fail with 5.1.0.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.1.1
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7

**Comment by treydock** [comment] 2019-01-26 14:48
It looks like something changed with keepalive events.  Once of the tests we run is being able to resolve an event and the event being resolved is a keepalive event.  If I skip the resolve of keepalive event I do not see test failures and still looking to be sure no segfaults.

**Comment by echlebek** [comment] 2019-01-29 19:24
@treydock I haven't managed to reproduce this crash unfortunately. Was there any more output to the log? It looks as though the panic trace is truncated.

**Comment by echlebek** [comment] 2019-01-29 19:34
The crash is occurring because the store is retrieving a nil event and then trying to operate on it. When the keepalive failure handler fired, the event was missing.

This can be reproduced by deleting an event before a keepalive failure happens. @treydock is that happening in the puppet tests? I was not able to trigger this by resolving an event, since that does not lead to an event being deleted.

**Comment by treydock** [comment] 2019-01-29 19:58
@echlebek Yes, part of the automated testing is also removing an event via sensuctl, so maybe it was that action that was triggering the crash.

**Closed** 2019-01-30 21:32 UTC
Labels: bug, ready-for-review
