### ISSUE TITLE
Cannot retrieve cluster health via sensuctl

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#2191] opened 2018-10-19 18:17 UTC
## Expected Behavior
I expect to see the cluster health when I run `sensuctl cluster health`

## Current Behavior
```
$ sensuctl cluster health
Error: GET "/health": Get https://127.0.0.1:8080/health?env=default&org=default: stream error: stream ID 1; INTERNAL_ERROR
```

On the backend logs:

```
Oct 19 18:14:27 ip-10-0-1-114 sensu-backend[21418]: {"component":"store","error":"context deadline exceeded","level":"error","member":15556450731175135856,"msg":"unhealthy cluster member","time":"2018-10-19T18:14:27Z"}
Oct 19 18:14:27 ip-10-0-1-114 sensu-backend[21418]: {"component":"apid","duration":"15003.349ms","level":"info","method":"GET","msg":"request completed","path":"/health","size":342,"status":200,"time":"2018-10-19T18:14:27Z"}
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): Sensu beta 6
* Installation method (packages, binaries, docker etc.): Terraform
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 16.04.4 LTS

**Comment by nikkiki** [comment] 2018-10-19 18:56
Dupe of https://github.com/sensu/sensu-go/issues/1964

**Closed by nikkiki** 2018-10-19 18:56 UTC
Labels: bug
