### ISSUE TITLE
Improve observability through prometheus metrics

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3281] opened 2019-09-16 20:24 UTC
Add prometheus metrics to sensu-backend that track the following things:

- The number of agents connected to each backend. (session.go)
- Metrics for check schedulers.
  - The number of interval check schedulers running, updated, or deleted.
  - The number of cron schedulers running, updated, or deleted.
  - The number of round robin interval schedulers running, updated, or deleted.
  - The number of round robin cron schedulers running, updated, or deleted.
  - Add the check name as a label to each metric.
- The number of etcd requests per second on each backend.
- Etcd request latency
  - 90th percentile
  - 99th percentile
  - 99.9th percentile
- The number of postgres transactions per second on each backend
- Postgres request latency
  - 90th percentile
  - 99th percentile
  - 99.9th percentile

**Comment by roganartu** [comment] 2020-03-31 18:34
Dupe of #3193? There's a bunch of suggested metrics in there. Some more I have been thinking about recently:

- histogram of event sizes
- gauge of number of entities (labelled by category, eg proxy vs regular vs ??)
- gauge of number of users (and really, probably number of all assets)
- timings of each step along the event pipeline, ultimately providing a way to see how long events are taking to be processed after being received
- histogram of queue delays. ie: comparing the check executed timestamp to the current time when an event hits each step of the pipeline, giving visibility into delays. This is useful if eg a step of the pipeline is failing and has a long timeout, causing queuing and delays (this has bitten us before)

**Closed** 2020-12-12 17:41 UTC
Labels: component:backend, enhancement, reviewed, wontfix
