### ISSUE TITLE
keepalive check won't create event after sensu-backend restart

### ISSUE THREAD

**Issue by nixwiz** [sensu/sensu-go#2584] opened 2019-01-03 23:14 UTC
Following a backend restart keepalive will fail to create events for stopped agents.
## Expected Behavior

Keepalive events would be generated.
## Current Behavior

Keepalive events are not generated following a backend restart.
## Steps to Reproduce (for bugs)

1. Start sensu-backend
2. Start sensu-agent on another server
3. Stop sensu-agent from step 2
4. Monitor entity for events, you will see the last seen time increasing, and verify event was generated for this keepalive failure once keepalive-timeout value is exceeded.
5. Start sensu-agent again and verify keepalive returns to passing
6. Stop and start sensu-backend
7. Verify keepalive for agent is still passing
8. Stop sensu-agent on entity from step 2
9. Monitor entity for events, you will see the last seen time increasing, eventually surpassing the keepalive-timeout value, but it will still show as OK and no event created.

This happened with both Linux and Windows agents.
## Context

This requires restarting **all** agents in the event of a backend restart.
## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
sensu-backend version 5.1.0#b2ea9fc, build b2ea9fcdb21e236e6e9a7de12225a6d90c786c57, built '2018-12-18T21:31:11+0000' (Linux)
sensu-agent version 5.1.0#b2ea9fc, build b2ea9fcdb21e236e6e9a7de12225a6d90c786c57, built '2018-12-18T21:31:11+0000' (Linux)
sensu-agent version 5.1.0#b2ea9fc, build b2ea9fcdb21e236e6e9a7de12225a6d90c786c57, built Wed, 19 Dec 2018 11:00:43 PST (Windows)
* Installation method (packages, binaries, docker etc.):  packages for Linux, binaries for Windows
* Operating System and version (e.g. Ubuntu 14.04):  Ubuntu 16.04 (backend and agent), Windows Server 2012 R2 Standard (agent)

**Comment by echlebek** [comment] 2019-01-04 23:07
This is a duplicate of #2530, so I'm going to close this issue in favour of the older one.

**Closed by echlebek** 2019-01-04 23:07 UTC
