### ISSUE TITLE
sensuctl entity create --interactive not working

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#2358] opened 2018-11-16 00:49 UTC
sensuctl entity create hmm --interactive
```
? Entity Class: proxy
Error: could not find field matching class
```
## Expected Behavior
I should be able to create entity interactively
## Current Behavior
interactive creation bails on entity class question.
neither 'proxy' nor 'agent' are allow as a entry strings

surprisingly this works:
`sensuctl entity create --entity-class "proxy"`

## Your Environment
sensu-go beta8
fedora 28

**Comment by nikkiki** [comment] 2018-11-16 01:13
Thanks for filing this Jef! I would say this is a dupe of https://github.com/sensu/sensu-go/issues/2344 since interactive mode is the culprit. I’m going to close this out in favor of that.

**Closed by nikkiki** 2018-11-16 01:13 UTC
