### ISSUE TITLE
[Check] Python check exit codes do not affect Event Status

### ISSUE THREAD

**Issue by malinlub** [sensu/sensu-go#1861] opened 2018-07-23 20:59 UTC
Exit codes from python check are still identified as status=0 in event 

## Expected Behavior
If python exit status in check is different than OK, so WARN, CRIT, UNKNOWN handler is able to do specific trigger, resolve actions etc.

## Current Behavior
Currently all exit statuses(1,2) simulated in check are still identified in event as status=0

## Steps to Reproduce (for bugs)
1. **docker run -d --name sensu-backend -p 127.0.0.1:2380:2380 -p 127.0.0.1:3000:3000 -p 127.0.0.1:8080:8080 -p 0.0.0.0:8081:8081 -v /opt/sensu_backend_data:/var/lib/sensu:rw -v /opt/sensu_backend_config:/etc/sensu:ro sensuapp/sensu-go:latest sensu-backend start**
2. **yum install sensu-agent sensu-cli** (both ...-2.0.0~nightly+20180723-1.x86_64)
3. **service sensu-agent start** (etc/sensu/agent.yml [agent.yml.pdf](https://github.com/sensu/sensu-go/files/2220963/agent.yml.pdf))
4. **sensuctl configure** (127.0.0.1:8080, org:default, env:default, user,pass:default)
5. **pip install sensu_plugin**
6. **Create myCheck.py** ([myCheck.py.pdf](https://github.com/sensu/sensu-go/files/2221007/myCheck.py.pdf))
7. **sensuctl create -f check.json** ([check.json.pdf](https://github.com/sensu/sensu-go/files/2220964/check.json.pdf))
8. **sensuctl check set-publish CheckCheck true**
9. **sensuctl event list** (here we can see that by usage of sensu-plugin-python tested WARN and CRITICAL messages have both Event status=0)
<img width="762" alt="screen shot 2018-07-23 at 22 45 59" src="https://user-images.githubusercontent.com/6599195/43102005-339be85a-8eca-11e8-8f61-7ef6590d6e07.png">
 
## Context
I would like to create trigger/resolve combo with pagerduty handler but if event identification of checks is wrong handler will not work properly

## Your Environment
**sensuctl**
sensu-ctl version 2.0.0-beta.1-1#f70b9f8, build f70b9f8a14ea926e4ce85467beecfe5cf731513d, built 2018-05-08T04:09:22+0000

**sensu-agent** 
sensu-agent version 2.0.0-beta.1-1#f70b9f8, build f70b9f8a14ea926e4ce85467beecfe5cf731513d, built 2018-05-08T04:09:05+0000

**sensu-backend in docker** 
backend version”
sensu-backend version 2.0.0-beta.2-2#30607d5, build 30607d50f966a438bcb06055ffc0f0cbc20240f4, built 2018-06-28T23:19:06+0000

CentOS Linux release 7.5.1804 (Core)

**Comment by echlebek** [comment] 2018-08-13 16:10
Hi @malinlub, I wasn't able to reproduce your issue with the latest release. However, I think you might be running into this issue: https://github.com/sensu/sensu-go/issues/1732

The problem is a result of our naming of Check and CheckConfig data types. (Our initial design was to only accept checks as "CheckConfig", but `sensuctl create` threw a wrench in that.) This has been worked around since being discovered and should no longer present a problem for users. Sorry for the inconvenience.

From what you describe, you're running a build from May 2018. This issue was resolved since then, so I think if you upgrade to the latest beta or nightly the problem should be cleared up for you. Please be aware we are now publishing docker images to https://hub.docker.com/r/sensu/sensu/. Can you try that and let us know if that sorts things out?

**Comment by oferrigni** [comment] 2018-08-20 16:10
Closing as fixed. If issue recurs, please reopen this issue. Thanks so much!

**Closed by oferrigni** 2018-08-20 16:10 UTC
Labels: next-for-development
