### ISSUE TITLE
Proxy request attributes do not match agent entities

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#2799] opened 2019-03-14 18:50 UTC
## Expected Behavior

As an operator I can configure a check using proxy requests attributes to run on behalf of any entity, regardless of entity class.

## Current Behavior

Proxy request attributes match only entities whose entity class is `proxy`

## Steps to Reproduce (for bugs)
1. Write a check configuration which uses proxy request entity attributes to generate check requests for one or more known agent entities
2. Note that no check requests are generated because no proxy entities match

## Context

Although the name of the "proxy check request" feature implies it is only for entities of class `proxy`, there are use cases for running checks on behalf of an agent entity and associating the results with that entity.

For example, consider a scenario where one or more agents make use of a tool like the Prometheus node_exporter with the sensu-prometheus-collector to send measurements to the sensu-backend for storage in InfluxDB.  In such a scenario, operators may wish to run checks against the measurements being stored in InfluxDB -- raising alerts when thresholds are breached or particular trends are observed -- but each individual agent reporting measurements may not have a network route or  firewall ACLs sufficient for accessing the InfluxDB server to run these checks.

In Sensu 1.x the proxy check request feature can be used to designate some number of agents as pollers who would run checks against the measurements stored in InfluxDB and associate the results of those checks with the system those measurements relate to. I think it makes sense to make that same capability available in Sensu Go.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.3.0
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): Centos 7

**Comment by nikkiki** [comment] 2019-03-28 21:54
I've confirmed that the behavior described is not actually occurring. Proxy requests attempt to match entity attributes on all entities, regardless of the proxy class. Nonetheless, this issue was difficult to debug because the entity attribute in question was somewhat complex `entity.subscriptions.indexOf("match") >= 0` and there was no verbose logging to indicate the matched entities.

Action items:
- @cwjohnston has filed https://github.com/sensu/sensu-enterprise-go/issues/303 which will hopefully lead to a tighter feedback loop regarding javascript expressions
- I have opened https://github.com/sensu/sensu-go/pull/2844 to improve the logging experience around proxy requests and matched entities.

Closing this out in favor of the action items.

**Closed by nikkiki** 2019-03-28 21:54 UTC
