### ISSUE TITLE
[Web UI] TypeError: Cannot read property 'nodes' of undefined

### ISSUE THREAD

**Issue by pmjensen** [sensu/sensu-go#2065] opened 2018-09-14 16:44 UTC
## Current Behavior

Dashboard fails to load.  Get error.  
## Steps to Reproduce (for bugs)

Errors in dashboard started after updating entity subscriptions with sensuctl. 

sensuctl entity update sensu.xxxxxx.aws
? Class: agent
? Subscriptions: entity:sensu.xxxxxx.aws,linux
? Organization: default
? Environment: default
OK

## Context

**Web UI Stack Trace:**

at `EventsContainer.render` ([src/components/partials/EventsList/EventsList.js:220](https://github.com/sensu/sensu-go/blob/249a69d/dashboard/src/components/partials/EventsList/EventsList.js#L220))
at `l` (node_modules/react-dom/cjs/react-dom.production.min.js:131)
at `beginWork` (node_modules/react-dom/cjs/react-dom.production.min.js:138)
at `e` (node_modules/react-dom/cjs/react-dom.production.min.js:176)
at `f` (node_modules/react-dom/cjs/react-dom.production.min.js:176)
at `G` (node_modules/react-dom/cjs/react-dom.production.min.js:182)
at `x` (node_modules/react-dom/cjs/react-dom.production.min.js:181)
at `n` (node_modules/react-dom/cjs/react-dom.production.min.js:181)
at `B` (node_modules/react-dom/cjs/react-dom.production.min.js:180)
at `v` (node_modules/react-dom/cjs/react-dom.production.min.js:179)
at `Object.enqueueForceUpdate` (node_modules/react-dom/cjs/react-dom.production.min.js:110)
at `Query.viRO.E.forceUpdate` (node_modules/react/cjs/react.production.min.js:12)
at `Query.oJmH._.Query.o.updateCurrentData` (node_modules/react-apollo/Query.js:87)
at `Object.next` (node_modules/react-apollo/Query.js:69)
at `notifySubscription` (node_modules/zen-observable/lib/Observable.js:126)

Component Stack:

```
in EventsContainer
in l
in withApollo(EventsContainer)
in div
in MobileFullWidthContent
in WithStyles
in div
in Query
in Query
in EventsContent
in QueryParams
in Route
in withRouter(QueryParams)
in withQueryParams(EventsContent)
in Route
in Switch
in div
in div
in div
in AppLayout
in WithStyles
in div
in div
in Loader
in WithStyles
in Query
in Query
in EnvironmentView
in Route
in ConditionalRoute
in AuthenticatedRoute
in Query
in Apollo(AuthenticatedRoute)
in Switch
in MuiThemeProvider
in ThemeProvider
in AppThemeProvider
in Connect(AppThemeProvider)
in ApolloProvider
in Provider
in AppRoot
in Route
in withRouter(AppRoot)
in WithStyles
in Router
in BrowserRouter
in ErrorBoundary
```

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): `249a69d`
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by ccressent** [comment] 2018-09-14 16:47
Thanks for the report @pmjensen!
What you are reporting looks to me like a duplicate of #2062.

**Closed** 2018-09-24 18:32 UTC
Labels: web-ui
