### ISSUE TITLE
When moving an agent from one namespace to another, the keepalive event in the new namespace never goes non-ok

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-go#3483] opened 2019-12-23 18:01 UTC
## Expected Behavior
The keepalive event for an entity representing an agent, after that agent has been re-configured to a new namespace, should go into a non-ok state if the sensu-backend loses communication with that agent.

## Current Behavior
The keepalive event for an entity representing an agent, after that agent has been re-configured to a new namespace, never goes into a non-ok state if the sensu-backend loses communication with that agent.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)

1. Create a backend and agent that goes into the default namespace.
2. Create a new namespace.
3. Reconfigure the agent to belong to that new namespace.
4. Delete the old entity representing the agent from the default namespace.
5. Stop the agent process to force a communication failure.
6. Observe that even after the keepalive time out for warning, the event for the keepalive stays in an ok status.

## Context
As a user, there are times where I would like to move the entity representing an agent to a different namespace.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.14.2
* Installation method (packages, binaries, docker etc.): packages

**Comment by palourde** [comment] 2020-01-09 20:14
@cwjohnston @rgeniesse I could not reproduce this bug on master. Were you able to reproduce it yourself? If so, could you try again with the latest commit on sensu-go or sensu-enterprise-go?

Here's what I did:

First, on a clean install, I created two namespaces:
```sh
$ s namespace list
   Name
 ─────────
  default
  dev
```

Then, I started the agent specified the `default` namespace:
```sh
$ s event list --all-namespaces
  Entity     Check                            Output                          Status   Silenced             Timestamp
 ──────── ─────────── ────────────────────────────────────────────────────── ──────── ────────── ───────────────────────────────
  whisky   keepalive   No keepalive sent from whisky for 16 seconds (>= 15)        1   false      2020-01-09 15:06:08 -0500 EST

```

I restarted the agent and specified the `dev` namespace:
```sh
$ s event list --all-namespaces
  Entity     Check                                  Output                                Status   Silenced             Timestamp
 ──────── ─────────── ────────────────────────────────────────────────────────────────── ──────── ────────── ───────────────────────────────
  whisky   keepalive   No keepalive sent from whisky for 16 seconds (>= 15)                    1   false      2020-01-09 15:06:28 -0500 EST
  whisky   keepalive   Keepalive last sent from whisky at 2020-01-09 15:06:34 -0500 EST        0   false      2020-01-09 15:06:34 -0500 EST
```

From that point, I deleted the entity that belongs to the `default` namespace:
```sh
$ s entity list --all-namespaces
    ID     Class     OS     Subscriptions             Last Seen
 ──────── ─────── ──────── ─────────────── ───────────────────────────────
  whisky   agent   darwin   entity:whisky   2020-01-09 15:06:12 -0500 EST
  whisky   agent   darwin   entity:whisky   2020-01-09 15:06:54 -0500 EST
$ s entity delete whisky --namespace default
? Are you sure you would like to delete resource 'whisky'? Yes
Deleted
```

Finally, I inspected the events in the `dev` namespace:
```sh
$ s event list --namespace dev
  Entity     Check                            Output                          Status   Silenced             Timestamp
 ──────── ─────────── ────────────────────────────────────────────────────── ──────── ────────── ───────────────────────────────
  whisky   keepalive   No keepalive sent from whisky for 45 seconds (>= 15)        1   false      2020-01-09 15:07:59 -0500 EST
```

**Comment by rgeniesse** [comment] 2020-01-09 23:23
@palourde I am unable to reproduce this on 5.16.1 and see the warning in the UI as well. That is only important as we never checked using sensuctl as well.

@cwjohnston can you review my instructions and the test above to see if there are any steps missing in reproducing this? I know we did see this happen in the UI even after the old entity in the original namespace was deleted. Thanks!

**Comment by portertech** [comment] 2020-01-13 18:30
CR to follow up on this.

**Comment by cwjohnston** [comment] 2020-01-14 19:39
I am not able to reproduce this on 5.14.2, seeing failing keepalive in both namespaces as expected (did not delete from default namespace): 

![2020-01-14 at 12 27 PM](https://user-images.githubusercontent.com/148017/72376287-f16d7e80-36ca-11ea-8aff-c25be9cf93fc.png)

**Comment by cwjohnston** [comment] 2020-01-14 20:32
I overlooked this note previously:

> I am unable to reproduce this on 5.16.1 and see the warning in the UI as well. That is only important as we never checked using sensuctl.

In my 5.14.2 test environment, the web UI matches the sensuctl output as expected.

I've also tested this while using the Postgres datastore, same result in both sensuctl and web UI -- keepalive goes non-ok in second namespace as expected.

**Comment by palourde** [comment] 2020-01-23 15:45
I'm gonna close this issue for now but do not hesitate to re-open it if we can figure out a way to reproduce it!

**Closed by palourde** 2020-01-23 15:45 UTC
Labels: bug
