### ISSUE TITLE
keepalive-critical-timeout doesn't work in agent.yml

### ISSUE THREAD

**Issue by edgan** [sensu/sensu-go#4203] opened 2021-02-12 22:04 UTC
I read the documentation at https://docs.sensu.io/sensu-go/6.1/observability-pipeline/observe-schedule/agent/#keepalive-configuration-flags, and tried to add keepalive-critical-timeout to my /etc/sensu/agent.yml. On trying to restart the service it fails to start. Remove the new line from agent.yml, and it starts again. Yet keepalive-warning-timeout works just fine.

  I also tried `sensu-agent start --keepalive-critical-timeout 300`, and it did at least run. I didn't test if it functioned properly. I have tested keepalive-warning-timeout in agent.yml and it does function properly.

  I am not sure if this is a bug via an inconsistency between options allowed in the yaml vs the command line, or if the option actually doesn't exist but is still in the documentation.
  
Package:
  `ii  sensu-go-agent                    6.2.4-4013                                 amd64        Sensu Go Agent`

Distribution:
`Ubuntu 16.04.3 LTS`

**Comment by fguimond** [comment] 2021-03-18 20:07
This appears to be working as expected. Using the `--keepalive-warning-timeout 45 --keepalive-critical-timeout 90` command line arguments I was able to observe events being generated after 45 (warning) and 90 (critical) seconds of downtime.

```
Keepalive last sent from sensu-francis.local at 2021-03-18 15:57:07 -0400 EDT
Warning: No keepalive sent from sensu-francis.local for 45 seconds (>= 45)
Critical: No keepalive sent from sensu-francis.local for 90 seconds (>= 90)
```

Similarly with the following agent.yml configuration I was able to observe the expected results.

```
keepalive-warning-timeout: 55
keepalive-critical-timeout: 110
```

```
Keepalive last sent from sensu-francis.local at 2021-03-18 15:59:46 -0400 EDT
No keepalive sent from sensu-francis.local for 55 seconds (>= 55)
No keepalive sent from sensu-francis.local for 111 seconds (>= 110)
```

**Comment by portertech** [comment] 2021-03-22 17:24
Closing this one as we are unable to reproduce the failure.

**Comment by amdprophet** [comment] 2021-04-01 23:56
Reopening as we appear to be running into the same issue occasionally.

**Comment by portertech** [comment] 2021-04-19 17:21
Unable to reproduce the agent start failure when using this flag.

**Closed by portertech** 2021-04-19 17:21 UTC
Labels: bug, needs-investigation
