### ISSUE TITLE
Sensu Agent failing to reconnect correctly when network interruption occurs

### ISSUE THREAD

**Issue by guipe** [sensu/sensu-go#4274] opened 2021-04-28 11:34 UTC
## Expected Behavior
When network interruption occurs between Sensu agent and Sensu Backend (mTLS), agent can again register to Sensu backend when interruption is finished.

## Current Behavior
When network interruption occurs, Sensu agent cannot register again to Sensu backend.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
When a network disconnection occurs, agent cannot reconnect to Sensu backend correctly. Keepalive checks failed and notify our OnCall teams.
Sensu backend never accept agent reconnection until we restart Sensu backend container.

**Keepalive failed even if:**
- we restart sensu agent
- we are trying to stop agent 1 hour and start again

When a disconnection occurs, agent cannot reconnect to Sensu backend, and we can see multiples CLOSE_WAIT connections on Sensu-backend container:
`tcp      254      0 ::ffff:172.18.0.6:8081  ::ffff:172.18.0.4:32776 CLOSE_WAIT  -`

**Traefik logs**(multiple lines like that, 172.18.0.6 = sensu-backend, 172.18.0.4 = traefik ):
`reverse-proxy              | time="2021-04-28T09:20:15Z" level=error msg="Error during connection: read tcp 172.18.0.4:41328->172.18.0.6:8081: read: connection reset by peer"
`
**Sensu agent logs:**
```
Apr 27 08:00:35 agent1.example.com sensu-agent[12899]: {"component":"agent","level":"info","msg":"connecting to backend URL \"wss://backend.sensu.example.com:443\"","time":"2021-04-27T08:00:35+02:00"}
Apr 27 08:00:35 agent1.example.com sensu-agent[12899]: {"component":"agent","header":"Accept: application/octet-stream","level":"debug","msg":"setting header","time":"2021-04-27T08:00:35+02:00"}
Apr 27 08:00:50 agent1.example.com sensu-agent[12899]: {"component":"agent","error":"read tcp 192.168.228.20:58402-\u003e159.100.240.146:443: i/o timeout","level":"error","msg":"reconnection attempt failed","time":"2021-04-27T08:00:50+02:00"}
```

**Sensu-backend logs:**
No error logs appears

Could you help us on this issue?

## Your Environment
Docker environment:

    Traefik 2.4 (redirect agent mTLS connection to Sensu backend)
    Sensu backend 6.2.7
    Sensu agent 6.2.7

Sensu agent => Traefik => Sensu Backend

Sensu agent communicates through mTLS.

**Comment by portertech** [comment] 2021-05-04 18:13
It seems that there is an issue when Traefik is used to proxy the agent transport connection. Are you able to test a group of Sensu agents without Traefik? Additional debugging and reproduction details would be helpful.

**Comment by guipe** [comment] 2021-05-05 14:50
We configure 5 agents which bypass Traefik reverse proxy using iptables routing.

4 agents have had the issue in the past, and 1 never had the issue. We'll keep you posted if we see the error happening again with these 5 agents.

Let us know what additional debugging and details you need.

Thanks!

**Comment by javierwilson** [comment] 2021-05-05 21:51
I have the exact same issue, sensu-go backend and agent versions 6.2.7.  No containers, the backend is ec2 instance and some agents are physical instances and some are ec2 instances.
Multiples CLOSE_WAIT connections start to build up on the backend, and keepalive alerts are triggered, so far, the only way to resolve it has been to restart the backend.  I've had the same problem with previous versions too.
Some agents use a proxy to connect to the backend but many do not, the issue is the same in either case.

**Comment by javierwilson** [comment] 2021-06-17 14:11
UPDATE: Since upgrading to 6.3.0 (server and agents) we have no longer seen (not even a single case) of keepalive failing (when it shouldn't) no more CLOSE_WAIT connection status piling up either. Thanks! I am not sure which patch/PR solved the issue.

**Comment by echlebek** [comment] 2022-02-09 23:45
Thanks @javierwilson, closing this out since no further issues seem to be occurring.

**Closed by echlebek** 2022-02-09 23:45 UTC
Labels: component:agent
