### ISSUE TITLE
authproviders API nesting metadata under spec

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#3442] opened 2019-11-30 16:40 UTC
## Expected Behavior

I'd expect the `/authproviders` API `GET` to match documentation and have top level key of `metadata`

## Current Behavior

Currently the `metadata` key is empty but there is `metadata` key under `spec` that has `name`.

## Steps to Reproduce (for bugs)

```
[root@sensu-backend ~]# cat ad.json 
{
  "Type": "ad",
  "api_version": "authentication/v2",
  "spec": {
    "servers": [
      {
        "host": "127.0.0.1",
        "binding": {
          "user_dn": "cn=binder,cn=users,dc=acme,dc=org",
          "password": "P@ssw0rd!"
        },
        "group_search": {
          "base_dn": "dc=acme,dc=org"
        },
        "user_search": {
          "base_dn": "dc=acme,dc=org"
        }
      }
    ]
  },
  "metadata": {
    "name": "activedirectory2"
  }
}

[root@sensu-backend ~]# sensuctl create -f ad.json 

[root@sensu-backend ~]# curl -q -k -H "Authorization: Bearer $TOKEN" https://sensu-backend.example.com:8080/api/enterprise/authentication/v2/authproviders 2>/dev/null | python -m json.tool
[
    {
        "api_version": "authentication/v2",
        "metadata": {},
        "spec": {
            "groups_prefix": "",
            "metadata": {
                "name": "activedirectory2"
            },
            "servers": [
                {
                    "binding": {
                        "password": "P@ssw0rd!",
                        "user_dn": "cn=binder,cn=users,dc=acme,dc=org"
                    },
                    "client_cert_file": "",
                    "client_key_file": "",
                    "default_upn_domain": "",
                    "group_search": {
                        "attribute": "member",
                        "base_dn": "dc=acme,dc=org",
                        "name_attribute": "cn",
                        "object_class": "group"
                    },
                    "host": "127.0.0.1",
                    "insecure": false,
                    "port": 636,
                    "security": "tls",
                    "trusted_ca_file": "",
                    "user_search": {
                        "attribute": "sAMAccountName",
                        "base_dn": "dc=acme,dc=org",
                        "name_attribute": "displayName",
                        "object_class": "person"
                    }
                }
            ],
            "username_prefix": ""
        },
        "type": "ad"
    }
]

```

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): CI BUILD from 11/30: `sensu-backend version 5.15.0, build 0436b97f7ee6b1a7aa5a23bbdd7b5243239be137, built 2019-11-30T01:36:14Z`
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7

**Comment by treydock** [comment] 2019-11-30 16:41
CC @ghoneycutt

**Comment by treydock** [comment] 2019-11-30 23:39
This is also happening for etcd-replicators URL:

```
[root@sensu-backend ~]# curl -q -k -H "Authorization: Bearer $TOKEN" https://sensu-backend.example.com:8080/api/enterprise/federation/v1/etcd-replicators | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   376  100   376    0     0   3874      0 --:--:-- --:--:-- --:--:--  3916
[
    {
        "api_version": "federation/v1",
        "metadata": {},
        "spec": {
            "api_version": "core/v2",
            "ca_cert": "/path/to/ssl/trusted-certificate-authorities.pem",
            "cert": "/path/to/ssl/cert.pem",
            "insecure": true,
            "key": "/path/to/ssl/key.pem",
            "metadata": {
                "name": "role_replicator"
            },
            "namespace": "",
            "replication_interval_seconds": 30,
            "resource": "Role",
            "url": "http://127.0.0.1:3379"
        },
        "type": "EtcdReplicator"
    }
]
```

**Comment by nikkixdev** [comment] 2019-12-02 19:48
I believe this is a dupe of https://github.com/sensu/sensu-enterprise-go/issues/704 (which is already in progress!), could you confirm that the original issue satisfies the issue you're describing here?

**Comment by treydock** [comment] 2019-12-02 19:54
@nikkixdev I get Github 404 page when I try to access that repo. I am guessing that repo is private?

**Comment by nikkixdev** [comment] 2019-12-02 19:59
🤦‍♂ oops, yeah it is haha. I'll share the contents of the issue here, as it doesn't contain anything that's not already public knowledge.

# Inconsistent payloads with API and sensuctl payloads

The payloads returned by the API and sensuctl are not the same. Sensuctl resolves the embedded metadata in the spec, and displays it at the highest level of the resource, however the API prints the literal struct.
```
$ sensuctl dump federation/v1.Cluster --format wrapped-json
{
  "type": "Cluster",
  "api_version": "federation/v1",
  "metadata": {
    "name": "my_cluster"
  },
  "spec": {
    "api_urls": [
      "http://10.0.0.1:8080",
      "http://10.0.0.2:8080",
      "http://10.0.0.3:8080"
    ]
  }
}
```

## Expected Behavior
`GET /api/enterprise/federation/v1/clusters/my_cluster`
```
{
    "type": "Cluster",
    "api_version": "federation/v1",
    "metadata": {
         "name": "my_cluster"
    },
    "spec": {
        "api_urls": [
            "http://10.0.0.1:8080",
            "http://10.0.0.2:8080",
            "http://10.0.0.3:8080"
        ]
    }
}
```

## Current Behavior
`GET /api/enterprise/federation/v1/clusters/my_cluster`
```
{
    "type": "Cluster",
    "api_version": "federation/v1",
    "metadata": {},
    "spec": {
        "metadata": {
            "name": "my_cluster"
        },
        "api_urls": [
            "http://10.0.0.1:8080",
            "http://10.0.0.2:8080",
            "http://10.0.0.3:8080"
        ]
    }
}
```

## Possible Solution
The generic controller should implement the same logic used by sensuctl to resolve the metadata.

## Context
API docs are inconsistent with what is happening.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): https://github.com/sensu/sensu-enterprise-go/commit/bca51e05f365cf8bda00362022de69b514f96ff7
* Installation method (packages, binaries, docker etc.): binaries
* Operating System and version (e.g. Ubuntu 14.04): MacOS Catalina

**Comment by treydock** [comment] 2019-12-02 21:18
That looks to be the same issue I'm having. All the `/enterprise/` API endpoints share this issue as far as I can tell.

**Comment by nikkixdev** [comment] 2019-12-02 21:32
This has definitely sparked some good internal discussion, thanks for filing these issues. I'm going to close this out as a dupe, and I would expect a fix to ship in the next release!

**Closed by nikkixdev** 2019-12-02 21:32 UTC
Labels: triage
