### ISSUE TITLE
include agent version in entity information

### ISSUE THREAD

**Issue by ninjasloth22** [sensu/sensu-go#3266] opened 2019-09-09 22:18 UTC
For agent type entities, it would be useful to have the agent version reported back to the backend.
This would help in easily filtering and identifying agent's that may be out of date. 
For example with the release of 5.12 there were changes in the asset spec that allowed multiple builds. 
If the agent was not on the correct version you would end up with.
error getting assets for event: error fetching asset: Get : unsupported protocol scheme ""

It would be usefully to be able to quickly audit agent versions.

**Comment by palourde** [comment] 2019-09-25 13:12
Hi @ninjasloth22, I'll go ahead and close this issue since it's a duplicate of https://github.com/sensu/sensu-go/issues/2637. For reference, we currently have an open PR that implements this.

**Closed by palourde** 2019-09-25 13:12 UTC
