### ISSUE TITLE
"context deadline exceeded" error message is too generic

### ISSUE THREAD

**Issue by trombik** [sensu/sensu-go#3792] opened 2020-05-25 11:07 UTC
many part of the backend code use context with `WithTimeout`. they do not always throw exception with details. they just throw "context deadline exceeded" error. this makes debugging extremely difficult.

## Expected Behavior

when timeout occurs, throws an error with more contexts, such as, who threw the error? what was the code doing? so that users can identify what the real cause is.

## Current Behavior

the backend (possibly others) throw "context deadline exceeded".

## Possible Solution

ensure to return error with the context.

## Steps to Reproduce (for bugs)

there are many ways to reproduce. the easiest way is:

1. try to enable TLS in the backend
2. make mistakes
3. start the backend

## Context

while I was trying to enable TLS, the backend always throws the error. I know it IS my fault, but it does not tell what the real issue is. to enable TLS, you need to change at least 20 configuration flags in `backend.yml`, which is not documented in the official documentation. if the backend gave me more context in errors, it would have been (slightly) easier.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.20.0
* Installation method (packages, binaries, docker etc.): my own package
* Operating System and version (e.g. Ubuntu 14.04): FreeBSD 12.1

**Comment by echlebek** [comment] 2020-05-25 21:27
This can be traced to a bug in etcd 3.3: https://github.com/etcd-io/etcd/issues/9400

We need to upgrade to at least etcd 3.4 to fix this, but etcd 3.4 was published as a broken Go module, so we can't upgrade to it. We have to wait for etcd 3.5, which should be published some time this year.

See also https://github.com/sensu/sensu-go/issues/3729, https://github.com/sensu/sensu-go/issues/3649, and https://github.com/sensu/sensu-go/issues/3663, which are related to this issue.

**Comment by calebhailey** [comment] 2020-08-31 05:15
Looks like etcd 3.5 is still in progress: https://github.com/etcd-io/etcd/milestone/37

**Comment by portertech** [comment] 2021-02-08 17:52
Will be closed by #3739

**Comment by portertech** [comment] 2021-04-19 17:38
We will confirm the issue has been fixed after merging https://github.com/sensu/sensu-go/pull/4229

**Comment by amdprophet** [comment] 2021-05-31 17:26
I wasn't able to reproduce this on the main branch which now has Etcd 3.4. If this continues to happen after the next release (6.4.0), please reopen this.

**Closed by amdprophet** 2021-05-31 17:26 UTC
Labels: bug, component:backend, component:etcd
