### ISSUE TITLE
Deleting entities should cause associated events to be deleted

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#2690] opened 2019-02-05 20:50 UTC
## Expected Behavior
When an entity is deleted, its associated events should be deleted as well. This would bring us in line with how 1.x works, and also in line with how deregistration works.

## Current Behavior
Entities are deleted but events remain.

## Possible Solution
Implement deregistration logic in the entity API.

**Comment by palourde** [comment] 2019-05-29 20:09
Duplicate of https://github.com/sensu/sensu-go/issues/2846

**Closed by palourde** 2019-05-29 20:09 UTC
Labels: 1.x parity, enhancement
