### ISSUE TITLE
Bug: sensuctl create panics when given a user object

### ISSUE THREAD

**Issue by roganartu** [sensu/sensu-go#2821] opened 2019-03-21 18:37 UTC
`sensuctl create` panics with a nil point dereference if it is given a User object.

## Expected Behavior
When invoking sensuctl with a valid User spec, a user matching the spec is created (or an existing user with the same name is updated).

## Current Behavior
`sensuctl` panics with a nil pointer dereference.

This appears to happen because:
1) The user is "successfully" parsed in that it produces no errors, but the resulting `resource` object is `nil`.
2) There is a bug here (https://github.com/sensu/sensu-go/blob/5.3.0/cli/commands/create/create.go#L157) where less than 10 resource validation errors does not result in an error being returned, so the calling function continues to attempt to create the invalid resource(s).

## Possible Solution
Return an error if _any_ provided resource fails validation.

As a user, I'm somewhat surprised to find that `sensuctl create` will simply ignore <10 invalid resources (with a log message, but this tool is run in a CI pipeline for us so the logs are ignored if there's no build failure). I think if this invalid-resource-tolerance is still desired it should be opt-in with a cli option (eg: `--allow-invalid 10` or something where the default is 0).

It also begs the question, is it intentional that `sensuctl create` doesn't work with User specs? The docs suggest it is intentional: https://docs.sensu.io/sensu-go/5.3/sensuctl/reference/#sensuctl-create-resource-types. Why is that? As a user I would like to be able to use the same `sensuctl create`-driven config-as-code process to enforce consistency of some default accounts with limited privileges (eg: read-only accounts for wallboards etc)

## Steps to Reproduce (for bugs)

```
$ cat user.json
{
  "type": "User",
  "api_version": "core/v2",
  "metadata": {},
  "spec": {
    "disabled": false,
    "groups": [],
    "username": "test",
    "password": "password"
  }
}
$ sensuctl create --file user.json
error validating resource 0: resource is nil
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa57242]

goroutine 1 [running]:
github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/cli/client.(*RestClient).PutResource(0xc0002007e0, 0xc000225240, 0x4, 0xc000225244, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, ...)                                                                                   
        /go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/cli/client/generic.go:68 +0x42
github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/cli/commands/create.PutResources(0x7f792c153170, 0xc0002007e0, 0xc0002a17c0, 0x1, 0x1, 0x0, 0x0)                                                                                                         
        /go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/cli/commands/create/create.go:184 +0xef
github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/cli/commands/create.execute.func1(0xc0002a2c80, 0x146d7b0, 0x0, 0x0, 0x0, 0x0)                                                                                                                           
        /go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/sensu/sensu-go/cli/commands/create/create.go:70 +0x212
github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra.(*Command).execute(0xc0002a2c80, 0x146d7b0, 0x0, 0x0, 0xc0002a2c80, 0x146d7b0)                                                                                                                              
        /go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra/command.go:753 +0x473
github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00020fb80, 0xc0002a4280, 0xc0002a4280, 0xc0002a4c80)                                                                                                                                 
        /go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra/command.go:843 +0x2fd
github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra.(*Command).Execute(0xc00020fb80, 0xc00026c0f0, 0x0)
        /go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/spf13/cobra/command.go:791 +0x2b
main.main()
        /go/src/github.com/sensu/sensu-enterprise-go/cmd/sensuctl/main.go:34 +0xcc
```

It's important to note that an invalid User spec also creates the same issue, but an invalid eg Check spec doesn't, so this seems to be exclusively a User issue:
```
$ echo '{"type": "User", "api_version": "core/v2", "spec": {}}' | sensuctl create 2>&1 | rg panic
panic: runtime error: invalid memory address or nil pointer dereference
$ echo '{"type": "Check", "api_version": "core/v2", "spec": {}}' | sensuctl create 2>&1 | rg panic

```

## Your Environment
```
$ sensuctl version
sensuctl version 5.3.0#379593a, build 379593a8859315e746da28eedfdc8ae4907091fa, built 2019-03-07T19:00:37Z
```

**Comment by palourde** [comment] 2019-05-08 15:55
Hi @roganartu 

I apologize for the delay. It seems that this issue is now fixed, I couldn't reproduce it with the latest version:

```
$ cat bin/user.json
{
  "type": "User",
  "api_version": "core/v2",
  "metadata": {},
  "spec": {
    "disabled": false,
    "groups": [],
    "username": "test",
    "password": "password"
  }
}
$ sensuctl create -f bin/user.json
$ sensuctl user list
  Username       Groups       Enabled
 ────────── ──────────────── ─────────
  admin      cluster-admins   true
  test                        true
```

Please let us know if you still face this problem with the latest binaries.

Thanks!

**Closed by palourde** 2019-05-08 15:55 UTC
