### ISSUE TITLE
BUG: sensuctl not respecting HTTP_PROXY nor http_proxy

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#3381] opened 2019-11-05 20:20 UTC
Looks like sensuctl isn't respecting either variant of the the http proxy environment variable

## Expected Behavior
I should be able to set either HTTP_PROXY or http_proxy prior to calling sensuctl and have the requests routed through the proxy when the sensu-backend url is NOT "localhost" or "127.0.0.1".

Localhost is handled as a special case by the underlying golang package, so proxy will always be ignored when using localhost
 
## Current Behavior
proxy isn't used

## Steps to Reproduce (for bugs)
Using a Fedora laptop with local sensu-backend install

1. Create a hostname alias `sensu-local-backend`  for `127.0.0.1` 
2. sensuctl configure using `http://sensu-local-backend:8080` and confirm `sensuctl entity list` works
3. Installed tinyproxy on localhost running on 8888
4. test access to sensu-backend api using wget with tinyproxy
```http_proxy="http://127.0.0.1:8888" wget -q -O - http://sensu-local-backend:8080/version```
5. check tinyproxy log to ensure proxy activity was captured
```sudo cat /var/log/tinyproxy/tinyproxy.log```
6. test HTTP_PROXY with sensuctl request
```HTTP_PROXY="http://127.0.0.1:8888" sensuctl entity list```
7. confirm tinyproxy log does NOT show proxy activity
8. test http_proxy with sensuctl request
```http_proxy="http://127.0.0.1:8888" sensuctl entity list```
7. confirm tinyproxy log does NOT show proxy activity

## Context
Originally reported on Discourse:
https://discourse.sensu.io/t/sensuctl-and-sensu-api-server-behind-a-corporate-proxy/1431

## Your Environment
Sensu 5.14.2 rpm packages on Fedora 29 laptop

**Comment by echlebek** [comment] 2019-11-06 18:33
I believe the issue is that the `resty` library is not respecting the way the Go HTTP client works. I would like to replace this library with the standard `net/http.Client`.

**Comment by pstadt** [comment] 2019-11-29 07:25
I am not sure which process has to download stuff if I do for example `sensuctl asset update xyz`.
But this is a major showstopper for the migration from sensu-core to sensu-go.

Backend and agent have defined proxy environment variables, sensuctl too.

**Comment by echlebek** [comment] 2020-02-22 18:31
Fixed in https://github.com/sensu/sensu-go/pull/3555

**Closed by echlebek** 2020-02-22 18:31 UTC
Labels: bug, technical-debt
