### ISSUE TITLE
token substitution should support integers

### ISSUE THREAD

**Issue by exitquote** [sensu/sensu-go#2729] opened 2019-02-15 19:03 UTC
Currently I'm unable to use token substitution for the "interval" field in check definitions, because it requires an integer.  Example:

`"interval": "{{.labels.load_interval | default 3600}}"`

If I don’t enclose this value in quotes, it’s not valid json, and if I do, Go tries to parse it as a string and I get `{"message":"json: cannot unmarshal string into Go struct field CheckConfig.interval of type uint32","code":0}`

## Expected Behavior

I'd like to be able to use token substitution for the interval value, because if I can't it means repeating my efforts by creating otherwise identical check definitions for machines that need the check to run more frequently.  The same goes for ttl, etc.

## Current Behavior

The check field for "interval" can't be set with token substitution.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): all 5.1.1
* Installation method (packages, binaries, docker etc.): yum install for agents and sensuctl; docker for sensu-backend
* Operating System and version (e.g. Ubuntu 14.04): Centos 7.4

**Comment by annaplotkin** [comment] 2019-02-27 21:52
@nikkiki to review

**Comment by nikkiki** [comment] 2019-03-01 21:40
Thanks for filing this issue! I'm able to reproduce the issue you are describing. Unfortunately, neither Sensu 1.x or Sensu Go support token substitution for integers (see [token data type limitations](https://docs.sensu.io/sensu-core/1.7/reference/checks/#token-data-type-limitations)).

> As part of the substitution process, Sensu converts all tokens to strings. This means that tokens cannot be used for bare integer values or to access individual list items.
> 
> For example, token substitution cannot be used for specifying a check interval because the interval attribute requires an integer value. But token substitution can be used for alerting thresholds since those values are included within the command string.

The same can be said for Go, as it is more explicit with its types. I'll leave this issue open right now for discussion, as I imagine it may be a useful feature for many. However, I'm not confident that this can be achieved without a breaking change such as changing interval types to strings - a very undesirable approach.

One potential workaround could be to use the cron field, since that's already a string, for example ` cron: "{{ .labels.load_interval | default '* * 3 * *' }}"`. This approach would likely require sensu-go to substitute tokens before resource validation and creation, or some other change of workflow in order for it to work.

**Comment by palourde** [comment] 2019-05-08 16:08
Just circling back to this issue: one other thing to consider is that token substitution happens on the agent side, once the check has been scheduled by the backend. Therefore, you can't use token substitution on fields required by the scheduler, like the interval, because the scheduler only schedules the check once, via its subscription; it does not send the check request to each entity individually based on their labels or things like this.

Because of this, and because allowing token substitution for integer values would basically require a major breaking change, I'll just go ahead and close this issue.

**Closed by palourde** 2019-05-08 16:08 UTC
Labels: enhancement, needs-discussion
