### ISSUE TITLE
Service executables should be capable of printing their own default configuration

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#3415] opened 2019-11-21 01:06 UTC
## Feature Suggestion

Sensu service executables should be capable of printing their default configuration.

## Possible Implementation

Add a subcommand to sensu-backend and sensu-agent which generates yaml output representing service configuration parameters and their default values.

Example: `sensu-backend print-defaults > /etc/sensu/backend.yml`

## Context

Currently the installation documentation suggests downloading `https://docs.sensu.io/sensu-go/latest/files/agent.yml` as the default configuration. If application defaults change, this file must also be updated.

We also provide an agent.yml.example under `/usr/share/doc` through our system packages, but the full path to those files changes with the package version, and those files are not available to those using our containers and/or binary-only artifacts. 

Implementing a feature like this allows the service executable to be the source of truth, removing the need for ongoing maintenance of example config files in both packaging and documentation.

**Comment by calebhailey** [comment] 2020-02-07 17:04
Looks like my issue #3548 might be a duplicate of this. I'm recommending a slightly different interface that would facilitate generating fully populated configuration files, but otherwise very similar ideas. Let me know if I should close my issue and comment on this one.

**Comment by portertech** [comment] 2020-08-10 17:44
@amdprophet to comment.

**Comment by amdprophet** [comment] 2020-08-14 03:30
The example configs we ship with Linux packages are currently the same across all supported Linux distributions. This is subject to change if we add supported distributions and/or if new versions of distributions enforce new path requirements.

I'd love to see a command that prints the OS defaults but I don't believe we should rely on it for packages. We may be able to remove the version from the path to the example configs if it will help.

**Comment by portertech** [comment] 2020-08-17 17:20
We are considering introducing a breaking change (>= 7.x), using relative paths.

**Closed** 2021-03-06 07:53 UTC
Labels: component:agent, component:backend, feature, low hanging :grapes:, needs-discussion, wontfix
