### ISSUE TITLE
Entity and assets with arm7 architecture are not matching up

### ISSUE THREAD

**Issue by espenaf** [sensu/sensu-go#3563] opened 2020-02-15 08:02 UTC
## Expected Behavior

When adding an asset with arm7 architecture support to an arm7 entity, the asset should be downloaded and ready to be used. 

## Current Behavior

Arm7 based entity like the Raspberry Pi 4 is being registered by the sensu-agent as an 'arm' architecture, not an 'arm7' architecture. The entity does however have an arm_version=7 modifier, but that does not seem to add any value here. When trying to add the asset, no entity.system.arch filter are being match:

```
Feb 15 08:45:30 powerpi sensu-agent[30091]: {"asset":"Salamek/sensu-go-load-check","component":"asset-manager","entity":"powerpi","level":"info","msg":"asset includes builds, using builds instead of asset","time":"2020-02-15T08:45:30+01:00"}
Feb 15 08:45:30 powerpi sensu-agent[30091]: {"asset":"Salamek/sensu-go-load-check","component":"asset-manager","entity":"powerpi","filter":["entity.system.os == 'linux'","entity.system.arch == 'amd64'"],"level":"debug","msg":"entity not filtered, not installing asset build","time":
Feb 15 08:45:30 powerpi sensu-agent[30091]: {"asset":"Salamek/sensu-go-load-check","component":"asset-manager","entity":"powerpi","filter":["entity.system.os == 'windows'","entity.system.arch == 'amd64'"],"level":"debug","msg":"entity not filtered, not installing asset build","time
Feb 15 08:45:30 powerpi sensu-agent[30091]: {"asset":"Salamek/sensu-go-load-check","component":"asset-manager","entity":"powerpi","filter":["entity.system.os == 'darwin'","entity.system.arch == '386'"],"level":"debug","msg":"entity not filtered, not installing asset build","time":"
Feb 15 08:45:30 powerpi sensu-agent[30091]: {"asset":"Salamek/sensu-go-load-check","component":"asset-manager","entity":"powerpi","filter":["entity.system.os == 'darwin'","entity.system.arch == 'amd64'"],"level":"debug","msg":"entity not filtered, not installing asset build","time"
Feb 15 08:45:30 powerpi sensu-agent[30091]: {"asset":"Salamek/sensu-go-load-check","component":"asset-manager","entity":"powerpi","filter":["entity.system.os == 'linux'","entity.system.arch == 'armv7'"],"level":"debug","msg":"entity not filtered, not installing asset build","time":
Feb 15 08:45:30 powerpi sensu-agent[30091]: {"asset":"Salamek/sensu-go-load-check","component":"asset-manager","entity":"powerpi","filter":["entity.system.os == 'linux'","entity.system.arch == 'arm64'"],"level":"debug","msg":"entity not filtered, not installing asset build","time":
Feb 15 08:45:30 powerpi sensu-agent[30091]: {"asset":"Salamek/sensu-go-load-check","component":"asset-manager","entity":"powerpi","filter":["entity.system.os == 'linux'","entity.system.arch == '386'"],"level":"debug","msg":"entity not filtered, not installing asset build","time":"2
Feb 15 08:45:30 powerpi sensu-agent[30091]: {"asset":"Salamek/sensu-go-load-check","component":"asset-manager","entity":"powerpi","level":"debug","msg":"entity not filtered from any asset builds, not installing asset","time":"2020-02-15T08:45:30+01:00"}
```

## Possible Solution

Editing the asset deploy info with a new 'arm' architecture makes asset work a given check again. Like this:

```
ORIGINAL:
    {
      "url": "https://assets.bonsai.sensu.io/3dd25f7f07489959a729cf2a7392087df91bb2c8/sensu-go-cpu-check_0.0.4_linux_armv7.tar.gz",
      "sha512": "0d261e2b8ee90fb3752e323263594b4982093cef207a32657dbcec68797ead1cc1a8a9cdebab8d1440ae3f96a14fb6c1502142cd1add377eeea26d822b2f6d58",
      "filters": [
        "entity.system.os == 'linux'",
        "entity.system.arch == 'armv7'"
      ],
      "headers": null
    },
ADDED:
    {
      "url": "https://assets.bonsai.sensu.io/3dd25f7f07489959a729cf2a7392087df91bb2c8/sensu-go-cpu-check_0.0.4_linux_armv7.tar.gz",
      "sha512": "0d261e2b8ee90fb3752e323263594b4982093cef207a32657dbcec68797ead1cc1a8a9cdebab8d1440ae3f96a14fb6c1502142cd1add377eeea26d822b2f6d58",
      "filters": [
        "entity.system.os == 'linux'",
        "entity.system.arch == 'arm'"
      ],
      "headers": null
    },
```
Agent after adding new asset:

```
Feb 15 08:45:40 powerpi sensu-agent[30091]: {"asset":"go-cpu-checks","component":"asset-manager","entity":"powerpi","level":"info","msg":"asset includes builds, using builds instead of asset","time":"2020-02-15T08:45:40+01:00"}
Feb 15 08:45:40 powerpi sensu-agent[30091]: {"asset":"go-cpu-checks","component":"asset-manager","entity":"powerpi","filter":["entity.system.os == 'windows'","entity.system.arch == 'amd64'"],"level":"debug","msg":"entity not filtered, not installing asset build","time":"2020-02-15T
Feb 15 08:45:40 powerpi sensu-agent[30091]: {"asset":"go-cpu-checks","component":"asset-manager","entity":"powerpi","filter":["entity.system.os == 'linux'","entity.system.arch == 'armv7'"],"level":"debug","msg":"entity not filtered, not installing asset build","time":"2020-02-15T08
Feb 15 08:45:40 powerpi sensu-agent[30091]: {"asset":"go-cpu-checks","component":"asset-manager","entity":"powerpi","filter":["entity.system.os == 'linux'","entity.system.arch == 'arm'"],"level":"debug","msg":"entity filtered, installing asset build","time":"2020-02-15T08:45:40+01:
```

I guess editing the entity from 'arm' to 'arm7' might also work, but I have not tried. 

## Steps to Reproduce (for bugs)

1. Setup Rapsberry Pi 4 with sensu-agent and sensuctl
2. sensuctl asset add Salamek/sensu-go-load-check:0.0.5
3. sensuctl check create check-load-go --command 'sensu-go-load-check -w 75 -c 90' --interval 60 --subscriptions arm --runtime-assets Salamek/sensu-go-load-check

## Context

Trying to add arm(7) based checks to a Raspberry Pi 4

## Your Environment

* sensu-backend 5.17.1 on amd64 and centos8 (another machine)
* sensuctl 5.17.1 arm7 binary download on Raspberry Pi 4
* sensu-agent 5.17.1 arm7 binary download on Raspberry Pi 4

**Comment by palourde** [comment] 2020-02-18 16:07
Hi @espenaf,

Thanks for reporting us this issue. This is actually not a bug with Sensu Go but the asset definitions defined by the plugins, e.g. https://github.com/asachs01/sensu-go-cpu-check/blob/dcdb2f64e57e708101a24bfe0538297edd119c66/.bonsai.yml#L28-L34

I believe that instead of using something like:

```yaml
filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'armv7'"
```

We will need to rely instead on the `GOARM` value instead:

```yaml
filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'arm'"
  -  "entity.system.arm_version == 7"
```

I don't have access to a Raspberry Pi right now but we probably need to test that out, update the [templates](https://github.com/sensu-community?utf8=%E2%9C%93&q=template&type=source&language=) and open PRs against plugins that rely on architectures like `armv7`.

**Comment by palourde** [comment] 2020-04-13 14:21
I'm gonna close this issue since we didn't receive any response and it appears to  be an issue with the asset itself.

**Closed by palourde** 2020-04-13 14:21 UTC
Labels: bug

**Comment by espenaf** [comment] 2020-10-02 06:32
@palourde Sorry about the late reply, but got some time to look into making an PR for the check-plugin-template now, but have a question. The arm[7] part of .bonsai.yml looks like this: 

`  - platform: "linux"
    arch: "armv7"
    asset_filename: "#{repo}_#{version}_linux_armv7.tar.gz"
    sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
    filter:
    -  "entity.system.os == 'linux'"
    -  "entity.system.arch == 'armv7'"
`
Modifying it with arm_version like you said is easy, but should we also all copies of the same declaration for arm5 and arm6?

**Comment by calebhailey** [comment] 2020-10-05 16:12
Looks like we should update the `.bonsai.yml` templates in the plugin template repos (e.g. https://github.com/sensu-community/check-plugin-template/blob/master/.bonsai.yml), and start updating existing assets to use the correct filters as well. 

In the interim, users can modify existing asset definitions as described above. 

Closing this issue in favor of the following: 

- https://github.com/sensu-community/check-plugin-template/issues/11
- https://github.com/sensu-community/handler-plugin-template/issues/16
- https://github.com/sensu-community/mutator-plugin-template/issues/8 
- https://github.com/sensu-community/sensuctl-plugin-template/issues/3

@espenaf can you open issues on the assets that are impacting you? That will help us get the ball rolling on updating the individual assets. Thanks!
