### ISSUE TITLE
sensuctl login via OIDC fails when the local configuration is absent or incomplete

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#4066] opened 2020-10-21 17:18 UTC
## Expected Behavior

`sensuctl login oidc` can succeed without having previously completed `sensuctl configure` with a successful login

## Current Behavior

`sensuctl login oidc` fails with an error when the cluster configuration on disk does not contain access and refresh tokens.

## Steps to Reproduce (for bugs)
0. with unconfigured sensuctl, attempt `sensuctl login oidc`. observe the error `Error: No API URL is defined. You can configure an API URL by running "sensuctl configure"`
1. configure sensuctl with an API URL but do not provide a username or password, as we want to be prompted for Oauth in browser
2. observe that the `configure` step fails with an authentication error, makes sense because no username/password
3. observe contents of  `$HOME/.config/sensu/sensuctl/cluster` and note that `access_token`, `refresh_token` and `expires_at` attributes are not present
4. attempt `sensuctl login oidc` again, new error `Error: Unable to locate credentials. You can configure credentials by running "sensuctl configure"`

## Possible solutions

Modify `sensuctl configure` to optionally initiates OIDC login during configuration

Allow `sensuctl login oidc` to accept arguments like API URL and any other arguments required for parity with `sensuctl configure`

## Context

This issue was mentioned in #4003 but 

Some users will be granted access to Sensu only via OIDC login, so they will not have a valid username/password to provide to sensuctl. 

Without a username/password pair for logging in w/o OIDC, a workaround is required: manually adding dummy value for `access_token` to the sensuctl cluster config file allows OIDC login to work as expected.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by palourde** [comment] 2020-10-26 15:51
Looks like a duplicate of https://github.com/sensu/sensu-enterprise-go/issues/708

**Comment by echlebek** [comment] 2020-10-27 18:08
Let's close this in favour of the issue in the enterprise repo, as it doesn't technically apply to the OSS project.

**Comment by echlebek** [comment] 2020-10-27 20:14
Re-opening this just to allow public tracking of this issue.

**Comment by portertech** [comment] 2020-11-03 19:15
Internal issue https://github.com/sensu/sensu-enterprise-go/issues/708

**Closed** 2020-11-23 17:42 UTC
Labels: component:sensuctl
