### ISSUE TITLE
[API] Implement HTTP patch

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#1158] opened 2018-03-13 17:27 UTC
To quote @palourde from https://github.com/sensu/sensu-go/pull/1154#issuecomment-372738245.

> As per RFC 5789, a PATCH request should only contain the changes to a resource. E.g. I If I want to update the URL of an asset, I should be able to issue a PATCH request to /assets/:id with the following body:
> 
> ```json
> {
>   "url": "https://foo.bar/baz.tar.gz"
> }
> ```
> 
> That's currently not the case.

The current behavior is:
1. Request payload is unmarshal'd into empty instance of the record. This ends up being problematic, as any of these fields that were not provided they remain the initial zero'd value.
1. Record is retrieved from the store.
1. Updatable fields from given instance are copied to the record retrieved from the store.
1. Record is persisted.

Likely intended behavior.
1. Request payload is unmarshal'd into map / or intermediary struct.
1. Slice any values that cannot be updated (ID, etc.)
1. Retrieve record from the store.
1. Copy values to record.
1. Persist.

**Comment by echlebek** [comment] 2018-05-31 17:46
@grepory thoughts on doing this for GA?

**Comment by annaplotkin** [comment] 2019-07-12 17:22
Could be done as a task in conjunction with 'prune'. Not a bug anymore.

**Comment by echlebek** [comment] 2020-04-13 16:42
Re-opening this, we are going to implement HTTP PATCH.

**Comment by ccressent** [comment] 2020-04-13 18:01
On the HTTP side, we should make sure to comply with [RFC 5789](https://tools.ietf.org/html/rfc5789) where it makes sense.

On the patch format side, we should really consider implementing (even if partially) the [JSON patch RFC](https://tools.ietf.org/html/rfc6902). I see 2 big reasons to do that:
- People can then leverage other tools that are RFC compliant to generate or work with their patches
- Patching can get really complex and using a format that's a web standard (even if it's not perfect) that was given a bit of thought should give us a chance to not have painted ourselves into a corner when/if we decide to support more and more complex operations

No matter the actual format of the patch we choose, we should be careful to consider what side effects we can create; for example, we shouldn't forget to validate the resulting object and check RBAC permissions on it before committing it! For example, if I have write permissions on an object in namespace A, I shouldn't be able to patch it to change its namespace to B without the backend checking that I indeed have permission to write in B.

**Comment by echlebek** [comment] 2020-04-13 18:18
> On the HTTP side, we should make sure to comply with RFC 5789 where it makes sense.
Do you think we need If-Match support and possibly even cache control before implementing patch? I am sympathetic to that.

> On the patch format side, we should really consider implementing (even if partially) the JSON patch RFC.
I dislike it, because it provides an avenue for patching to be complex, but the existence of a library providing support for it does soften my stance here.

(My view is that you can avoid most of the complexity of patching, and retain most of the value, by restricting it to top-level object fields. It's not going to satisfy all use cases but it's going to satisfy most. I think both JSON patch RFCs are overly complex, especially 6902, which implements what amounts to an RPC system.)

> No matter the actual format of the patch we choose, we should be careful to consider what side effects we can create; for example, we shouldn't forget to validate the resulting object and check RBAC permissions on it before committing it! For example, if I have write permissions on an object in namespace A, I shouldn't be able to patch it to change its namespace to B without the backend checking that I indeed have permission to write in B.

I would argue that such an operation should be disallowed entirely. You should not be able to modify a resource at a different URL from the one you specified. In fact, for our existing PUT handler, this type of operation is a 400.

**Comment by ccressent** [comment] 2020-11-03 19:58
I believe this issue should have been closed by the completion of #4015.

**Closed by ccressent** 2020-11-03 19:58 UTC
Labels: component:backend, feature, needs-discussion
