### ISSUE TITLE
Response filter parser failes to parse some AND expressions

### ISSUE THREAD

**Issue by tadeboro** [sensu/sensu-go#4224] opened 2021-03-14 18:49 UTC
## Expected Behavior

`GET /api/core/v2/namespaces/demo/checks?fieldSelector=check.publish%20%21%3D%20true%20%26%26%20%22linux%22%20in%20check.subscriptions` should return unpublished checks with a `linux` subscription.

## Current Behavior

The backend returns a 400 response stating `{"message":"unexpected token 'linux', expected an identifier after '\u0026\u0026'","code":1}`.

## Steps to Reproduce (for bugs)

`curl -v -H "Authorization: Bearer $ACCESS_TOKEN" -H "Content-Type: application/json" -G --data-urlencode 'fieldSelector=check.publish != true && "linux" in check.subscriptions' http://127.0.0.1:8080/api/core/v2/checks`

## Context

We discovered this issue while adding filtering support to the Sensu Go Python client and one of our tests failed when we were running queries against our Sensu Go backend. We also noticed that if we reverse the order of subexpressions into `"linux" in check.subscriptions && check.publish != true`, things do work. We can also get the expression to work if we drop the quotes around the `linux` word, but this is not always possible. For example, if our subscription name would contain a `-` character, the backend would respond with `{"message":"unexpected token 'invalid identifier: \"li-\"', expected an identifier after '\u0026\u0026'","code":1}`.

It looks like the `&&` operator does not like to have quoted string on its right side.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 6.1.3, 6.2.5
* Installation method (packages, binaries, docker etc.): Official sensu/sensu docker images

**Comment by portertech** [comment] 2021-03-16 18:16
Thanks for the issue and further context, this is very helpful!

Duplicate of https://github.com/sensu/sensu-enterprise-go/issues/1485

**Closed by portertech** 2021-03-16 18:16 UTC
