### ISSUE TITLE
Ability to apply filters to handler sets

### ISSUE THREAD

**Issue by ichilton** [sensu/sensu-go#3751] opened 2020-05-13 09:13 UTC
The documentation states:

> NOTE: Filters specified in a handler set definition have no effect. Filters must be specified in individual handler definitions.

However, it is still possible to apply filters to a handler set. I would argue this is a bug which causes confusion. If they are not allowed/processed, then it should not let you set them?

I would like to see that as a feature though.

It would be great to be able to apply filters to a handler set to filter events invoking the set.

Currently, if you wanted different filters on a set to the handlers on their own - you would have to duplicate each of the handlers and apply the desired filters each of those duplicates - which is going to get difficult to maintain very quickly.

Obviously the filters should only apply to events hitting the set, not events hitting the handlers directly, so that should be clarified in the docs.

**Comment by echlebek** [comment] 2020-05-13 18:45
cc @portertech, we should decide whether to allow filtering handler sets, or whether specifying filters on them is an error. Currently filters on handler sets are ignored without warning.

According to @palourde, classic sensu didn't permit filtering handler sets, but it's not clear if this was an explicit design decision.

**Comment by calebhailey** [comment] 2020-06-08 20:13
Is this a duplicate of https://github.com/sensu/sensu-go/issues/3353 ?

**Comment by echlebek** [comment] 2020-06-08 20:22
It does appear to be.

**Closed** 2020-12-12 23:36 UTC
Labels: component:pipeline, wontfix
