### ISSUE TITLE
Queue tests timing out after 3 minutes

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1280] opened 2018-04-10 16:55 UTC
In a recent PR, the Travis CI amd64 job failed to execute the queue integration tests. A timeout occurred.

The full log is here: https://sensu.slack.com/files/U7VLQBNSY/FA48GQX8B/queue_tests_timing_out.txt

**Comment by cyphus** [comment] 2018-04-16 18:32
I've gone through the logs and compared them to logs from a successful test run on macOS. The main issue here appears to be that the etcd clients are not closing after the tests.

## Log Analysis

The logs show hundreds of lines of connection refused errors, only stopping when the tests time out:

`WARNING: 2018/04/10 16:39:17 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:42555: connect: connection refused"; Reconnecting to {127.0.0.1:42555 0  <nil>}`

While successful tests also show connection refused errors, it will try 1-2 times per address, and then exit cleanly. The failing tests also have some context canceled logs sprinkled in with the connection errors, but these seem to be a side effect of clients not getting cleaned up.

`WARNING: 2018/04/10 16:39:06 grpc: addrConn.transportMonitor exits due to: context canceled`

The context canceled logs do not appear on a successful run.

## Potential reasons

- Golang's network code behaves differently on macOS and linux due to underlying differences in OSes, which may be responsible for some differences in networking errors.
- Go 1.10.1 changed some of the connection handling logic for connection refused errors. My successful runs are on 1.10.1 while Travis is building against Go 1.10. See https://github.com/golang/go/commit/bf0f69220255941196c684f235727fd6dc747b5c
- Looking through some of our etcd client code, we put requests into a FIFO queue (backend/queue/queue.go). What happens when those requests time out? Is it possible to retry indefinitely?
- Despite what I said during sprint planning, I don't think updating etcd or grpc would fix this, given the fact that the related issues I was looking at were from late 2017/early 2018 and we're on etcd 3.3.2 from March 8th. There is nothing relevant in etcd's changelog to suggest upgrading to 3.3.3.

**Comment by echlebek** [comment] 2018-04-16 20:55
@cyphus we probably don't want to retry queue operations indefinitely. Rather, we should fail after some backoff. The client can then try again, or make a request to another backend, in a clustered scenario.

**Comment by cyphus** [comment] 2018-04-17 18:47
Last night I was able to reproduce the issue locally and get some more information.

- To reproduce the issue, stop the Etcd server before the client establishes a connection. The client will leak grpc client goroutines, and will endlessly loop attempting to connect to the Etcd server, until killed by test timeout.
- This bug can potentially affect other tests -- if one client leaks grpc goroutines, all other clients in the same process will do the same unless explicitly closed.
- The goroutines being leaked are grpc client goroutines that are managed by Etcd clientv3.

At this point signs point to the dial timeout in the Etcd client getting lost somewhere. That, or the context cancel not propagating to grpc. Investigating further.

**Comment by echlebek** [comment] 2018-04-17 22:44
Excellent work in reproducing this!

**Comment by cyphus** [comment] 2018-04-18 00:10
Any call to Etcd clientv3's KV object will block indefinitely while the client tries to re-establish a connection to the server.

There's an etcd context manager called `WithRequireLeader` that is meant to auto-cancel contexts when no leader is available, but it doesn't apply to our test scenario, presumably because the tests use a single member cluster that has no leader.

I recommend adding a `txTimeout` member to the Queue struct and update all KV operations to use a timeout context. The timeout should cover any other uncommon client state that leads to indefinite looping as well.

What's a reasonable default value for `txTimeout`? We'd want to choose something that provides enough time for transactions to commit under load.

Also, going back to the original issue at hand, adding a transaction timeout would prevent the overall tests from timing out like what happened on that failed Travis build, but it wouldn't make the tests pass. It's hard to say what the underlying issue is here, because grpc reports connection errors even on successful test runs, and outputs from all the tests are jumbled together with no indication as to which message is from which test. Plus, since clients aren't being cleaned up after tests, all clients end up reporting connection errors via leaked goroutines. I want to reproduce this error without parallelization to be able to find the issue for sure.

I'm going to make a PR for queue test client cleanup. I can add in the recommended transaction timeout behavior if we want that too.

**Comment by cyphus** [comment] 2018-04-24 22:39
After being on vacation and coming back to this issue, I feel it would be best to attack this issue directly on the etcd level. Adding a transaction timeout would involve more code to workaround an issue that shouldn't come up in normal embedded etcd use.

I'm making a PR with the etcd client shutdown changes so the queue tests do not leak goroutines, but other than that I'm declaring this an etcd bug.

**Comment by echlebek** [comment] 2018-04-24 22:56
@cyphus do you think it's possible to produce a minimal reproduction of this bug?

**Closed** 2018-04-25 00:07 UTC
Labels: bug, ready-for-review, technical-debt
