### ISSUE TITLE
Backend can lockup when agents crash during registration

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#2431] opened 2018-11-28 04:06 UTC
It appears that a simple round robin check request does not get published if more than one entity is subscribed to the check. This occurs in a single and clustered environment.

## Expected Behavior
When a check's round robin field is set to `true`, I would expect the check to execute in a round robin fashion. For all entities subscribed to that check, only one entity will execute it each time it is published.

## Current Behavior
Schedulerd complains that there is an error publishing the round robin check request:
```
Nov 28 03:46:28 ip-10-0-1-171 sensu-backend[3404]: {"check":"round-robin","component":"schedulerd","error":"context deadline exceeded","level":"error","msg":"error publishing round robin check request","time":"2018-11-28T03:46:28Z"}
```
https://github.com/sensu/sensu-go/blob/3860ab4f37d6dc7b16a8650b040637871b10fa41/backend/schedulerd/round_robin_scheduler.go#L79

## Possible Solution
Investigate the `context deadline exceeded` error thrown by `PublishDirect`.
https://github.com/sensu/sensu-go/blob/3860ab4f37d6dc7b16a8650b040637871b10fa41/backend/schedulerd/round_robin_scheduler.go#L60-L61

## Steps to Reproduce (for bugs)
1. create the following check:
```
spec:
  check_hooks: []
  command: echo round-robin
  cron: ""
  handlers: []
  high_flap_threshold: 0
  interval: 10
  low_flap_threshold: 0
  metadata:
    annotations: null
    labels: null
    name: round-robin
    namespace: default
  output_metric_format: ""
  output_metric_handlers: []
  proxy_entity_name:
  publish: true
  round_robin: true
  runtime_assets: []
  stdin: false
  subdue: null
  subscriptions:
  - round-robin
  timeout: 0
  ttl: 0
type: CheckConfig
```
2. start 2 agents subscribed to `round-robin`
3. observe that no events are created for the check `round-robin`
4. observe the errors logged on the backend(s)

## Context
Round robin checks should work with more than one entity subscribed. That is the defining use case for a round robin check.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): https://github.com/sensu/sensu-go/commit/9f7978204c67a1186847ba9ef80492cebe952048
* Installation method (packages, binaries, docker etc.): packages deployed from terraform in aws
* Operating System and version (e.g. Ubuntu 14.04): backend: Ubuntu 16.04

**Comment by echlebek** [comment] 2018-11-28 06:49
This is a recent regression. I'm figuring out the commit that caused it.

**Comment by echlebek** [comment] 2018-11-28 06:59
So, I actually wasn't able to reproduce the issue. (tip of master, docker)

I used the check you pasted above, plus the following docker-compose:

```
version: '3'
services:
  backend1:
    image: sensu/sensu:master
    command: sensu-backend start --etcd-listen-client-urls http://0.0.0.0:2379 --etcd-name backend1 --etcd-initial-cluster backend1=http://backend1:2380,backend2=http://backend2:2380,backend3=http://backend3:2380 --etcd-initial-cluster-state new --etcd-initial-advertise-peer-urls http://backend1:2380 --state-dir /var/lib/sensu/etcd1 --etcd-listen-peer-urls http://0.0.0.0:2380 --log-level debug --debug
    hostname: backend1
    restart: always
    ports:
      - "2379:2379"
      - "2380:2380"
      - "8080:8080"
      - "8081:8081"
      - "6060:6060"
  backend2:
    image: sensu/sensu:master
    command: sensu-backend start --etcd-listen-client-urls http://0.0.0.0:2379 --etcd-name backend2 --etcd-initial-cluster backend1=http://backend1:2380,backend2=http://backend2:2380,backend3=http://backend3:2380 --etcd-initial-cluster-state new --etcd-initial-advertise-peer-urls http://backend2:2380 --state-dir /var/lib/sensu/etcd2 --etcd-listen-peer-urls http://0.0.0.0:2380 --log-level debug
    hostname: backend2
    restart: always
    ports:
      - "12379:2379"
      - "12380:2380"
      - "18080:8080"
      - "18081:8081"
  backend3:
    image: sensu/sensu:master
    command: sensu-backend start --etcd-listen-client-urls http://0.0.0.0:2379 --name backend3 --etcd-initial-cluster backend1=http://backend1:2380,backend2=http://backend2:2380,backend3=http://backend3:2380 --etcd-initial-cluster-state new --etcd-initial-advertise-peer-urls http://backend3:2380 --state-dir /var/lib/sensu/etcd3 --etcd-listen-peer-urls http://0.0.0.0:2380 --log-level debug
    hostname: backend3
    restart: always
    ports:
      - "22379:2379"
      - "22380:2380"
      - "28080:8080"
      - "28081:8081"
  agent1:
    image: sensu/sensu:master
    command: sensu-agent start --backend-url ws://backend1:8081 --subscriptions test,round-robin --log-level debug
    hostname: agent1
    restart: always
    depends_on:
      - backend1
      - backend2
      - backend3
  agent2:
    image: sensu/sensu:master
    command: sensu-agent start --backend-url ws://backend2:8081 --subscriptions test,round-robin --log-level debug
    hostname: agent2
    restart: always
    depends_on:
      - backend1
      - backend2
      - backend3
  agent3:
    image: sensu/sensu:master
    command: sensu-agent start --backend-url ws://backend3:8081 --subscriptions test,round-robin --log-level debug
    hostname: agent3
    restart: always
    depends_on:
      - backend1
      - backend2
      - backend3
```

I see the following events:
```
  Entity      Check        Output      Status   Silenced             Timestamp            
 ──────── ───────────── ───────────── ──────── ────────── ─────────────────────────────── 
  agent1   keepalive                        0   false      2018-11-27 22:58:56 -0800 PST  
  agent1   round-robin   round-robin        0   false      2018-11-27 22:58:53 -0800 PST  
                                                                                          
  agent2   keepalive                        0   false      2018-11-27 22:58:54 -0800 PST  
  agent2   round-robin   round-robin        0   false      2018-11-27 22:58:33 -0800 PST  
                                                                                          
  agent3   keepalive                        0   false      2018-11-27 22:58:55 -0800 PST  
  agent3   round-robin   round-robin        0   false      2018-11-27 22:58:43 -0800 PST  
```

**Comment by nikkiki** [comment] 2018-11-28 07:29
#### Were there other scheduling events occurring concurrently? Other round robin scheduling events?
I was able to reproduce this in the clustered staging environment with multiple concurrent events (no other round robin events). I was also able to reproduce this on a single backend in my local environment with no concurrent events.

#### What are the configurations of the two agents? (command line and yaml)
See sensu-staging for agent config.

Locally:
```
sensu-agent start --log-level debug --subscriptions round-robin --name agent-1
sensu-agent start --log-level debug --subscriptions round-robin --name agent-2 --api-port 4031
```

**Comment by echlebek** [comment] 2018-11-28 20:55
I was able to reproduce this with the config you show here, however, I noticed some problems with the way you are running the agents:

* --cache-dir is the same for both agents, so they would be trying to write to the same asset cache dir
* --socket-port is the same for both agents, so one would not be able to bind to 3030

When I launch the agents with this configuration, I also don't get keepalives for agent2.

When I resolve the problems with this configuration, keepalives and roundrobin work as expected.

I dumped the goroutine stack to get visibility into what was going on in the backend. It looks like the internal bus has locked up.

```
goroutine 92 [select]:
github.com/sensu/sensu-go/backend/pipelined.(*Pipelined).createPipelines.func1(0xc000994000, 0xc0000b32c0)
	/home/eric/go/src/github.com/sensu/sensu-go/backend/pipelined/pipelined.go:127 +0xea
created by github.com/sensu/sensu-go/backend/pipelined.(*Pipelined).createPipelines
	/home/eric/go/src/github.com/sensu/sensu-go/backend/pipelined/pipelined.go:124 +0x70

goroutine 93 [select]:
github.com/sensu/sensu-go/backend/pipelined.(*Pipelined).createPipelines.func1(0xc000994000, 0xc0000b32c0)
	/home/eric/go/src/github.com/sensu/sensu-go/backend/pipelined/pipelined.go:127 +0xea
created by github.com/sensu/sensu-go/backend/pipelined.(*Pipelined).createPipelines
	/home/eric/go/src/github.com/sensu/sensu-go/backend/pipelined/pipelined.go:124 +0x70

goroutine 94 [select, 3 minutes]:
github.com/sensu/sensu-go/backend/pipelined.(*Pipelined).createPipelines.func1(0xc000994000, 0xc0000b32c0)
	/home/eric/go/src/github.com/sensu/sensu-go/backend/pipelined/pipelined.go:127 +0xea
created by github.com/sensu/sensu-go/backend/pipelined.(*Pipelined).createPipelines
	/home/eric/go/src/github.com/sensu/sensu-go/backend/pipelined/pipelined.go:124 +0x70

goroutine 95 [select, 2 minutes]:
github.com/sensu/sensu-go/backend/pipelined.(*Pipelined).createPipelines.func1(0xc000994000, 0xc0000b32c0)
	/home/eric/go/src/github.com/sensu/sensu-go/backend/pipelined/pipelined.go:127 +0xea
created by github.com/sensu/sensu-go/backend/pipelined.(*Pipelined).createPipelines
	/home/eric/go/src/github.com/sensu/sensu-go/backend/pipelined/pipelined.go:124 +0x70

goroutine 96 [select, 2 minutes]:
github.com/sensu/sensu-go/backend/pipelined.(*Pipelined).createPipelines.func1(0xc000994000, 0xc0000b32c0)
	/home/eric/go/src/github.com/sensu/sensu-go/backend/pipelined/pipelined.go:127 +0xea
created by github.com/sensu/sensu-go/backend/pipelined.(*Pipelined).createPipelines
	/home/eric/go/src/github.com/sensu/sensu-go/backend/pipelined/pipelined.go:124 +0x70

goroutine 97 [select, 3 minutes]:
github.com/sensu/sensu-go/backend/pipelined.(*Pipelined).createPipelines.func1(0xc000994000, 0xc0000b32c0)
	/home/eric/go/src/github.com/sensu/sensu-go/backend/pipelined/pipelined.go:127 +0xea
created by github.com/sensu/sensu-go/backend/pipelined.(*Pipelined).createPipelines
	/home/eric/go/src/github.com/sensu/sensu-go/backend/pipelined/pipelined.go:124 +0x70

goroutine 274 [select, 2 minutes]:
github.com/sensu/sensu-go/backend/pipelined.(*Pipelined).createPipelines.func1(0xc000994000, 0xc0000b32c0)
	/home/eric/go/src/github.com/sensu/sensu-go/backend/pipelined/pipelined.go:127 +0xea
created by github.com/sensu/sensu-go/backend/pipelined.(*Pipelined).createPipelines
	/home/eric/go/src/github.com/sensu/sensu-go/backend/pipelined/pipelined.go:124 +0x70

goroutine 275 [select, 1 minutes]:
github.com/sensu/sensu-go/backend/pipelined.(*Pipelined).createPipelines.func1(0xc000994000, 0xc0000b32c0)
	/home/eric/go/src/github.com/sensu/sensu-go/backend/pipelined/pipelined.go:127 +0xea
created by github.com/sensu/sensu-go/backend/pipelined.(*Pipelined).createPipelines
	/home/eric/go/src/github.com/sensu/sensu-go/backend/pipelined/pipelined.go:124 +0x70

goroutine 276 [select, 1 minutes]:
github.com/sensu/sensu-go/backend/pipelined.(*Pipelined).createPipelines.func1(0xc000994000, 0xc0000b32c0)
	/home/eric/go/src/github.com/sensu/sensu-go/backend/pipelined/pipelined.go:127 +0xea
created by github.com/sensu/sensu-go/backend/pipelined.(*Pipelined).createPipelines
	/home/eric/go/src/github.com/sensu/sensu-go/backend/pipelined/pipelined.go:124 +0x70

goroutine 277 [select, 1 minutes]:
github.com/sensu/sensu-go/backend/pipelined.(*Pipelined).createPipelines.func1(0xc000994000, 0xc0000b32c0)
	/home/eric/go/src/github.com/sensu/sensu-go/backend/pipelined/pipelined.go:127 +0xea
created by github.com/sensu/sensu-go/backend/pipelined.(*Pipelined).createPipelines
	/home/eric/go/src/github.com/sensu/sensu-go/backend/pipelined/pipelined.go:124 +0x70

goroutine 278 [select]:
github.com/sensu/sensu-go/backend/eventd.(*Eventd).startHandlers.func1(0xc00016a1c0)
	/home/eric/go/src/github.com/sensu/sensu-go/backend/eventd/eventd.go:98 +0xfb
created by github.com/sensu/sensu-go/backend/eventd.(*Eventd).startHandlers
	/home/eric/go/src/github.com/sensu/sensu-go/backend/eventd/eventd.go:94 +0x43

goroutine 279 [select, 3 minutes]:
github.com/sensu/sensu-go/backend/eventd.(*Eventd).startHandlers.func1(0xc00016a1c0)
	/home/eric/go/src/github.com/sensu/sensu-go/backend/eventd/eventd.go:98 +0xfb
created by github.com/sensu/sensu-go/backend/eventd.(*Eventd).startHandlers
	/home/eric/go/src/github.com/sensu/sensu-go/backend/eventd/eventd.go:94 +0x43

goroutine 280 [select, 3 minutes]:
github.com/sensu/sensu-go/backend/eventd.(*Eventd).startHandlers.func1(0xc00016a1c0)
	/home/eric/go/src/github.com/sensu/sensu-go/backend/eventd/eventd.go:98 +0xfb
created by github.com/sensu/sensu-go/backend/eventd.(*Eventd).startHandlers
	/home/eric/go/src/github.com/sensu/sensu-go/backend/eventd/eventd.go:94 +0x43

goroutine 281 [select, 2 minutes]:
github.com/sensu/sensu-go/backend/eventd.(*Eventd).startHandlers.func1(0xc00016a1c0)
	/home/eric/go/src/github.com/sensu/sensu-go/backend/eventd/eventd.go:98 +0xfb
created by github.com/sensu/sensu-go/backend/eventd.(*Eventd).startHandlers
	/home/eric/go/src/github.com/sensu/sensu-go/backend/eventd/eventd.go:94 +0x43

goroutine 282 [select, 2 minutes]:
github.com/sensu/sensu-go/backend/eventd.(*Eventd).startHandlers.func1(0xc00016a1c0)
	/home/eric/go/src/github.com/sensu/sensu-go/backend/eventd/eventd.go:98 +0xfb
created by github.com/sensu/sensu-go/backend/eventd.(*Eventd).startHandlers
	/home/eric/go/src/github.com/sensu/sensu-go/backend/eventd/eventd.go:94 +0x43

goroutine 283 [select, 2 minutes]:
github.com/sensu/sensu-go/backend/eventd.(*Eventd).startHandlers.func1(0xc00016a1c0)
	/home/eric/go/src/github.com/sensu/sensu-go/backend/eventd/eventd.go:98 +0xfb
created by github.com/sensu/sensu-go/backend/eventd.(*Eventd).startHandlers
	/home/eric/go/src/github.com/sensu/sensu-go/backend/eventd/eventd.go:94 +0x43

goroutine 284 [select, 1 minutes]:
github.com/sensu/sensu-go/backend/eventd.(*Eventd).startHandlers.func1(0xc00016a1c0)
	/home/eric/go/src/github.com/sensu/sensu-go/backend/eventd/eventd.go:98 +0xfb
created by github.com/sensu/sensu-go/backend/eventd.(*Eventd).startHandlers
	/home/eric/go/src/github.com/sensu/sensu-go/backend/eventd/eventd.go:94 +0x43

goroutine 285 [select, 1 minutes]:
github.com/sensu/sensu-go/backend/eventd.(*Eventd).startHandlers.func1(0xc00016a1c0)
	/home/eric/go/src/github.com/sensu/sensu-go/backend/eventd/eventd.go:98 +0xfb
created by github.com/sensu/sensu-go/backend/eventd.(*Eventd).startHandlers
	/home/eric/go/src/github.com/sensu/sensu-go/backend/eventd/eventd.go:94 +0x43

goroutine 286 [select, 1 minutes]:
github.com/sensu/sensu-go/backend/eventd.(*Eventd).startHandlers.func1(0xc00016a1c0)
	/home/eric/go/src/github.com/sensu/sensu-go/backend/eventd/eventd.go:98 +0xfb
created by github.com/sensu/sensu-go/backend/eventd.(*Eventd).startHandlers
	/home/eric/go/src/github.com/sensu/sensu-go/backend/eventd/eventd.go:94 +0x43

goroutine 287 [select]:
github.com/sensu/sensu-go/backend/eventd.(*Eventd).startHandlers.func1(0xc00016a1c0)
	/home/eric/go/src/github.com/sensu/sensu-go/backend/eventd/eventd.go:98 +0xfb
created by github.com/sensu/sensu-go/backend/eventd.(*Eventd).startHandlers
	/home/eric/go/src/github.com/sensu/sensu-go/backend/eventd/eventd.go:94 +0x43

goroutine 190 [chan receive, 8 minutes]:
github.com/sensu/sensu-go/backend/store/etcd.(*Store).GetCheckConfigWatcher.func1(0xc00034ee40, 0x19f5740, 0xc0002c9ac0, 0xc0009a0540)
	/home/eric/go/src/github.com/sensu/sensu-go/backend/store/etcd/watchers.go:41 +0x6f1
created by github.com/sensu/sensu-go/backend/store/etcd.(*Store).GetCheckConfigWatcher
	/home/eric/go/src/github.com/sensu/sensu-go/backend/store/etcd/watchers.go:36 +0x7f

goroutine 104 [select, 8 minutes]:
github.com/sensu/sensu-go/backend/schedulerd.(*CheckWatcher).startWatcher(0xc0002c9b00)
	/home/eric/go/src/github.com/sensu/sensu-go/backend/schedulerd/check_watcher.go:86 +0x108
created by github.com/sensu/sensu-go/backend/schedulerd.(*CheckWatcher).Start
	/home/eric/go/src/github.com/sensu/sensu-go/backend/schedulerd/check_watcher.go:78 +0x143
```

**Comment by echlebek** [comment] 2018-11-28 20:58
Additionally, the agent that is last to try to write to the cache dir seems to lock up while trying to write to it. It never recovers.

**Comment by echlebek** [comment] 2018-11-28 21:06
It gets even crazier. Once this condition occurs, the backend does not recover even when restarted. It seems that the db becomes corrupted.

**Comment by nikkiki** [comment] 2018-11-28 21:58
It appears that there may be multiple issues here. One of which being that the round-robin issue is not consistently reproducible. I've fixed my agent configs to ensure there are no port collisions (although I do remember a point where the agent would fail to start up if it detected a collision).
```
sensu-agent start --cache-dir /Users/nattea/Desktop/cache/sensu-agent-1/ --log-level debug --subscriptions round-robin --name agent-1
sensu-agent start --cache-dir /Users/nattea/Desktop/cache/sensu-agent-2/ --log-level debug --subscriptions round-robin --name agent-2 --api-port 4031 --statsd-disable --disable-sockets
```
During this reproduction, the round-robin check executed when the agents were first started, but after restarting them, the same context deadline exceeded error occurred.

**Comment by nikkiki** [comment] 2018-11-29 00:43
Temporarily disabling round-robin scheduling until this issue is resolved: https://github.com/sensu/sensu-go/issues/2444

**Comment by echlebek** [comment] 2019-02-14 00:37
With the new round robin implementation, this issue will be obviated, as we are moving to a watcher-based model.

**Closed by echlebek** 2019-02-14 00:37 UTC
Labels: bug, needs-feature-spec
